2024-04-01 20:10:57,972 - INFO - Starting scheduler
2024-04-01 20:10:57,983 - INFO - Updater date and time: 2024-04-01 20:10:57.972698
2024-04-01 20:10:57,984 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-04-01 20:10:57,984 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-04-01 20:10:57,984 - INFO - Scheduler started
2024-04-01 20:10:57,985 - INFO - Current time of the scheduler: 2024-04-01 20:10:57.985171
2024-04-01 20:10:57,985 - INFO - Ending scheduler
2024-04-01 20:10:59,858 - INFO - Starting scheduler
2024-04-01 20:10:59,874 - INFO - Updater date and time: 2024-04-01 20:10:59.858913
2024-04-01 20:10:59,874 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-04-01 20:10:59,874 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-04-01 20:10:59,874 - INFO - Scheduler started
2024-04-01 20:10:59,874 - INFO - Current time of the scheduler: 2024-04-01 20:10:59.874539
2024-04-01 20:10:59,874 - INFO - Ending scheduler
2024-04-01 20:10:59,896 - INFO - Watching for file changes with StatReloader
2024-04-01 20:11:00,011 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-04-01 20:11:00 BST)" (scheduled at 2024-04-01 20:11:00+01:00)
2024-04-01 20:11:00,011 - INFO - Inside the procedure sequence
2024-04-01 20:11:00,011 - INFO - Inside the procedure sequence
2024-04-01 20:11:00,014 - INFO - The input start time: 2024-04-01 19:11:00
2024-04-01 20:11:00,014 - INFO - The input start time: 2024-04-01 19:11:00
2024-04-01 20:11:00,844 - ERROR - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-04-01 20:16:00 BST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\updater.py", line 67, in run_procedure_sequence
    run_IG(ticker)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\run_IG.py", line 153, in run_IG
    ig_service.create_session()
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 393, in create_session
    self._set_headers(response.headers, True)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 450, in _set_headers
    self.CLIENT_TOKEN = response_headers['CST']
                        ~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\requests\structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
           ~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'cst'
2024-04-01 20:11:09,161 - WARNING - Not Found: /tickers/ticker/9f53d106-491e-43bc-8f19-f91352ee4426/images/favicon.ico
2024-04-01 20:11:14,904 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-04-01 20:16:00 BST)" executed successfully
2024-04-01 20:21:10,539 - INFO - Watching for file changes with StatReloader
2024-04-01 20:21:20,454 - INFO - C:\Users\sunny\Desktop\Development\python\TradePro\prices\updater.py changed, reloading.
2024-04-01 20:21:22,504 - INFO - Starting scheduler
2024-04-01 20:21:22,504 - INFO - Updater date and time: 2024-04-01 20:21:22.504375
2024-04-01 20:21:22,504 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-04-01 20:21:22,504 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-04-01 20:21:22,504 - INFO - Scheduler started
2024-04-01 20:21:22,511 - INFO - Current time of the scheduler: 2024-04-01 20:21:22.511026
2024-04-01 20:21:22,511 - INFO - Ending scheduler
2024-04-01 20:21:22,527 - INFO - Watching for file changes with StatReloader
2024-04-01 20:25:07,058 - INFO - Starting scheduler
2024-04-01 20:25:07,059 - INFO - Updater date and time: 2024-04-01 20:25:07.059296
2024-04-01 20:25:07,059 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-04-01 20:25:07,059 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-04-01 20:25:07,059 - INFO - Scheduler started
2024-04-01 20:25:07,059 - INFO - Current time of the scheduler: 2024-04-01 20:25:07.059573
2024-04-01 20:25:07,059 - INFO - Ending scheduler
2024-04-01 20:25:08,875 - INFO - Starting scheduler
2024-04-01 20:25:08,875 - INFO - Updater date and time: 2024-04-01 20:25:08.875492
2024-04-01 20:25:08,875 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-04-01 20:25:08,875 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-04-01 20:25:08,875 - INFO - Scheduler started
2024-04-01 20:25:08,891 - INFO - Current time of the scheduler: 2024-04-01 20:25:08.891118
2024-04-01 20:25:08,891 - INFO - Ending scheduler
2024-04-01 20:25:08,905 - INFO - Watching for file changes with StatReloader
2024-04-01 20:25:39,122 - INFO - The input start time: 2024-04-01 18:25:00+00:00
2024-04-01 20:25:40,232 - ERROR - Internal Server Error: /prices/get-IG-prices/
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\views.py", line 155, in get_IG_prices
    run_IG(ticker_symbol, start_date, end_date)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\run_IG.py", line 157, in run_IG
    ig_service.create_session()
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 393, in create_session
    self._set_headers(response.headers, True)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 450, in _set_headers
    self.CLIENT_TOKEN = response_headers['CST']
                        ~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\requests\structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
           ~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'cst'
2024-04-01 20:25:40,418 - WARNING - Not Found: /favicon.ico
2024-04-01 20:25:46,397 - INFO - The input start time: 2024-04-01 18:25:00+00:00
2024-04-01 20:26:00,009 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-04-01 20:26:00 BST)" (scheduled at 2024-04-01 20:26:00+01:00)
2024-04-01 20:26:00,010 - INFO - Inside the procedure sequence
2024-04-01 20:26:00,014 - INFO - The input start time: 2024-04-01 19:26:00
2024-04-01 20:26:00,045 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-04-01 20:26:00 BST)" (scheduled at 2024-04-01 20:26:00+01:00)
2024-04-01 20:26:00,045 - INFO - Inside the procedure sequence
2024-04-01 20:26:00,108 - INFO - The input start time: 2024-04-01 19:26:00
2024-04-01 20:26:00,812 - ERROR - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-04-01 20:31:00 BST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\updater.py", line 71, in run_procedure_sequence
    run_IG(ticker)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\run_IG.py", line 157, in run_IG
    ig_service.create_session()
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 393, in create_session
    self._set_headers(response.headers, True)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 450, in _set_headers
    self.CLIENT_TOKEN = response_headers['CST']
                        ~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\requests\structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
           ~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'cst'
2024-04-01 20:26:01,204 - ERROR - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-04-01 20:31:00 BST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\updater.py", line 71, in run_procedure_sequence
    run_IG(ticker)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\run_IG.py", line 157, in run_IG
    ig_service.create_session()
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 393, in create_session
    self._set_headers(response.headers, True)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 450, in _set_headers
    self.CLIENT_TOKEN = response_headers['CST']
                        ~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\requests\structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
           ~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'cst'
2024-04-01 20:51:49,548 - INFO - Starting scheduler
2024-04-01 20:51:49,548 - INFO - Updater date and time: 2024-04-01 20:51:49.548455
2024-04-01 20:51:49,549 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-04-01 20:51:49,549 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-04-01 20:51:49,549 - INFO - Scheduler started
2024-04-01 20:51:49,550 - INFO - Current time of the scheduler: 2024-04-01 20:51:49.550580
2024-04-01 20:51:49,550 - INFO - Ending scheduler
2024-04-01 20:51:51,299 - INFO - Starting scheduler
2024-04-01 20:51:51,299 - INFO - Updater date and time: 2024-04-01 20:51:51.299578
2024-04-01 20:51:51,299 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-04-01 20:51:51,299 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-04-01 20:51:51,299 - INFO - Scheduler started
2024-04-01 20:51:51,299 - INFO - Current time of the scheduler: 2024-04-01 20:51:51.299578
2024-04-01 20:51:51,299 - INFO - Ending scheduler
2024-04-01 20:51:51,329 - INFO - Watching for file changes with StatReloader
2024-04-01 20:52:26,503 - WARNING - Not Found: /ml_models/about/images/favicon.ico
2024-04-01 20:52:41,365 - INFO - The input start time: 2024-04-01 18:00:00+00:00
2024-04-01 21:06:45,059 - INFO - Starting scheduler
2024-04-01 21:06:45,060 - INFO - Updater date and time: 2024-04-01 21:06:45.060888
2024-04-01 21:06:45,062 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-04-01 21:06:45,062 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-04-01 21:06:45,062 - INFO - Scheduler started
2024-04-01 21:06:45,063 - INFO - Current time of the scheduler: 2024-04-01 21:06:45.063223
2024-04-01 21:06:45,063 - INFO - Ending scheduler
2024-04-01 21:06:46,765 - INFO - Starting scheduler
2024-04-01 21:06:46,765 - INFO - Updater date and time: 2024-04-01 21:06:46.765953
2024-04-01 21:06:46,765 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-04-01 21:06:46,765 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-04-01 21:06:46,765 - INFO - Scheduler started
2024-04-01 21:06:46,765 - INFO - Current time of the scheduler: 2024-04-01 21:06:46.765953
2024-04-01 21:06:46,765 - INFO - Ending scheduler
2024-04-01 21:06:46,787 - INFO - Watching for file changes with StatReloader
2024-04-01 21:06:48,993 - WARNING - Not Found: /images/favicon.ico
2024-04-01 21:07:43,142 - INFO - Starting scheduler
2024-04-01 21:07:43,142 - INFO - Updater date and time: 2024-04-01 21:07:43.142137
2024-04-01 21:07:43,142 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-04-01 21:07:43,147 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-04-01 21:07:43,147 - INFO - Scheduler started
2024-04-01 21:07:43,148 - INFO - Current time of the scheduler: 2024-04-01 21:07:43.148350
2024-04-01 21:07:43,148 - INFO - Ending scheduler
2024-04-01 21:07:44,143 - INFO - Running job "run_procedure_sequence (trigger: date[2024-04-01 21:07:44 BST], next run at: 2024-04-01 21:07:44 BST)" (scheduled at 2024-04-01 21:07:44.142137+01:00)
2024-04-01 21:07:44,143 - INFO - Removed job ae6f5301f59143579a565d35504324cf
2024-04-01 21:07:44,143 - INFO - Inside the procedure sequence
2024-04-01 21:07:44,143 - INFO - The input start time: 2024-04-01 20:00:00
2024-04-01 21:07:44,709 - ERROR - Job "run_procedure_sequence (trigger: date[2024-04-01 21:07:44 BST], next run at: 2024-04-01 21:07:44 BST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\updater.py", line 71, in run_procedure_sequence
    run_IG(ticker)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\run_IG.py", line 158, in run_IG
    ig_service.create_session()
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 393, in create_session
    self._set_headers(response.headers, True)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 450, in _set_headers
    self.CLIENT_TOKEN = response_headers['CST']
                        ~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\requests\structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
           ~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'cst'
2024-04-01 21:07:44,993 - INFO - Starting scheduler
2024-04-01 21:07:44,994 - INFO - Updater date and time: 2024-04-01 21:07:44.994398
2024-04-01 21:07:44,995 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-04-01 21:07:44,995 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-04-01 21:07:44,995 - INFO - Scheduler started
2024-04-01 21:07:44,996 - INFO - Current time of the scheduler: 2024-04-01 21:07:44.996398
2024-04-01 21:07:44,996 - INFO - Ending scheduler
2024-04-01 21:07:45,012 - INFO - Watching for file changes with StatReloader
2024-04-01 21:07:46,004 - INFO - Running job "run_procedure_sequence (trigger: date[2024-04-01 21:07:45 BST], next run at: 2024-04-01 21:07:45 BST)" (scheduled at 2024-04-01 21:07:45.994398+01:00)
2024-04-01 21:07:46,005 - INFO - Inside the procedure sequence
2024-04-01 21:07:46,004 - INFO - Removed job 6171c8cc8dcc488aba52e5f359517f51
2024-04-01 21:07:46,007 - INFO - The input start time: 2024-04-01 20:00:00
2024-04-01 21:07:54,852 - INFO - Job "run_procedure_sequence (trigger: date[2024-04-01 21:07:45 BST], next run at: 2024-04-01 21:07:45 BST)" executed successfully
2024-04-01 21:09:35,332 - INFO - C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\run_IG.py changed, reloading.
2024-04-01 21:09:37,549 - INFO - Starting scheduler
2024-04-01 21:09:37,549 - INFO - Updater date and time: 2024-04-01 21:09:37.549157
2024-04-01 21:09:37,549 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-04-01 21:09:37,549 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-04-01 21:09:37,549 - INFO - Scheduler started
2024-04-01 21:09:37,549 - INFO - Current time of the scheduler: 2024-04-01 21:09:37.549157
2024-04-01 21:09:37,549 - INFO - Ending scheduler
2024-04-01 21:09:37,571 - INFO - Watching for file changes with StatReloader
2024-04-01 21:09:38,563 - INFO - Running job "run_procedure_sequence (trigger: date[2024-04-01 21:09:38 BST], next run at: 2024-04-01 21:09:38 BST)" (scheduled at 2024-04-01 21:09:38.549157+01:00)
2024-04-01 21:09:38,563 - INFO - Inside the procedure sequence
2024-04-01 21:09:38,563 - INFO - Removed job 31c7a2bdbe84406cb56173cd27fbb254
2024-04-01 21:09:38,568 - INFO - The input start time: 2024-04-01 21:00:00
2024-04-01 21:09:47,326 - INFO - Job "run_procedure_sequence (trigger: date[2024-04-01 21:09:38 BST], next run at: 2024-04-01 21:09:38 BST)" executed successfully
2024-04-01 21:11:11,904 - INFO - Starting scheduler
2024-04-01 21:11:11,904 - INFO - Updater date and time: 2024-04-01 21:11:11.904504
2024-04-01 21:11:11,904 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-04-01 21:11:11,904 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-04-01 21:11:11,904 - INFO - Scheduler started
2024-04-01 21:11:11,904 - INFO - Current time of the scheduler: 2024-04-01 21:11:11.904504
2024-04-01 21:11:11,904 - INFO - Ending scheduler
2024-04-01 21:11:12,922 - INFO - Running job "run_procedure_sequence (trigger: date[2024-04-01 21:11:12 BST], next run at: 2024-04-01 21:11:12 BST)" (scheduled at 2024-04-01 21:11:12.904504+01:00)
2024-04-01 21:11:12,922 - INFO - Inside the procedure sequence
2024-04-01 21:11:12,922 - INFO - Removed job bcab175c520044a69b884632df5bc420
2024-04-01 21:11:12,922 - INFO - The input start time: 2024-04-01 21:00:00
2024-04-01 21:11:13,556 - ERROR - Job "run_procedure_sequence (trigger: date[2024-04-01 21:11:12 BST], next run at: 2024-04-01 21:11:12 BST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\updater.py", line 71, in run_procedure_sequence
    run_IG(ticker)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\run_IG.py", line 158, in run_IG
    ig_service.create_session()
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 393, in create_session
    self._set_headers(response.headers, True)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 450, in _set_headers
    self.CLIENT_TOKEN = response_headers['CST']
                        ~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\requests\structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
           ~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'cst'
2024-04-01 21:11:13,714 - INFO - Starting scheduler
2024-04-01 21:11:13,714 - INFO - Updater date and time: 2024-04-01 21:11:13.714205
2024-04-01 21:11:13,714 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-04-01 21:11:13,714 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-04-01 21:11:13,714 - INFO - Scheduler started
2024-04-01 21:11:13,714 - INFO - Current time of the scheduler: 2024-04-01 21:11:13.714205
2024-04-01 21:11:13,714 - INFO - Ending scheduler
2024-04-01 21:11:13,737 - INFO - Watching for file changes with StatReloader
2024-04-01 21:11:14,725 - INFO - Running job "run_procedure_sequence (trigger: date[2024-04-01 21:11:14 BST], next run at: 2024-04-01 21:11:14 BST)" (scheduled at 2024-04-01 21:11:14.714205+01:00)
2024-04-01 21:11:14,726 - INFO - Inside the procedure sequence
2024-04-01 21:11:14,726 - INFO - Removed job 3969090a63354551ba5c27d4a505a312
2024-04-01 21:11:14,727 - INFO - The input start time: 2024-04-01 21:00:00
2024-04-01 21:11:15,433 - ERROR - Job "run_procedure_sequence (trigger: date[2024-04-01 21:11:14 BST], next run at: 2024-04-01 21:11:14 BST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\updater.py", line 71, in run_procedure_sequence
    run_IG(ticker)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\run_IG.py", line 158, in run_IG
    ig_service.create_session()
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 393, in create_session
    self._set_headers(response.headers, True)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 450, in _set_headers
    self.CLIENT_TOKEN = response_headers['CST']
                        ~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\requests\structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
           ~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'cst'
2024-04-01 21:11:16,890 - WARNING - Not Found: /images/favicon.ico
2024-04-01 21:11:21,376 - WARNING - Not Found: /tickers/images/favicon.ico
2024-04-01 21:11:26,891 - WARNING - Not Found: /tickers/ticker/9f53d106-491e-43bc-8f19-f91352ee4426/images/favicon.ico
2024-04-01 21:11:29,044 - WARNING - Not Found: /prices/delete-price/278411cc-7a92-4b66-8dbb-9ea45bb4cb94/images/favicon.ico
2024-04-01 21:11:43,177 - INFO - C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\run_IG.py changed, reloading.
2024-04-01 21:11:45,440 - INFO - Starting scheduler
2024-04-01 21:11:45,440 - INFO - Updater date and time: 2024-04-01 21:11:45.440474
2024-04-01 21:11:45,440 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-04-01 21:11:45,440 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-04-01 21:11:45,440 - INFO - Scheduler started
2024-04-01 21:11:45,440 - INFO - Current time of the scheduler: 2024-04-01 21:11:45.440474
2024-04-01 21:11:45,440 - INFO - Ending scheduler
2024-04-01 21:11:45,462 - INFO - Watching for file changes with StatReloader
2024-04-01 21:11:46,449 - INFO - Running job "run_procedure_sequence (trigger: date[2024-04-01 21:11:46 BST], next run at: 2024-04-01 21:11:46 BST)" (scheduled at 2024-04-01 21:11:46.440474+01:00)
2024-04-01 21:11:46,449 - INFO - Removed job ce519d7f9b5943e4805855f771178150
2024-04-01 21:11:46,449 - INFO - Inside the procedure sequence
2024-04-01 21:11:46,449 - INFO - The input start time: 2024-04-01 21:00:00
2024-04-01 21:11:47,014 - ERROR - Job "run_procedure_sequence (trigger: date[2024-04-01 21:11:46 BST], next run at: 2024-04-01 21:11:46 BST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\updater.py", line 71, in run_procedure_sequence
    run_IG(ticker)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\run_IG.py", line 158, in run_IG
    ig_service.create_session()
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 393, in create_session
    self._set_headers(response.headers, True)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 450, in _set_headers
    self.CLIENT_TOKEN = response_headers['CST']
                        ~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\requests\structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
           ~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'cst'
2024-04-01 21:12:05,190 - WARNING - Not Found: /prices/get-IG-prices/images/favicon.ico
2024-04-01 21:12:23,541 - INFO - The input start time: 2024-04-01 20:00:00+00:00
2024-04-01 21:12:24,484 - ERROR - Internal Server Error: /prices/get-IG-prices/
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\views.py", line 155, in get_IG_prices
    run_IG(ticker_symbol, start_date, end_date)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\run_IG.py", line 158, in run_IG
    ig_service.create_session()
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 393, in create_session
    self._set_headers(response.headers, True)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 450, in _set_headers
    self.CLIENT_TOKEN = response_headers['CST']
                        ~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\requests\structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
           ~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'cst'
2024-04-01 21:12:24,630 - WARNING - Not Found: /favicon.ico
2024-04-01 21:12:33,250 - INFO - The input start time: 2024-04-01 20:00:00+00:00
2024-04-01 21:12:34,323 - ERROR - Internal Server Error: /prices/get-IG-prices/
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\views.py", line 155, in get_IG_prices
    run_IG(ticker_symbol, start_date, end_date)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\run_IG.py", line 158, in run_IG
    ig_service.create_session()
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 393, in create_session
    self._set_headers(response.headers, True)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 450, in _set_headers
    self.CLIENT_TOKEN = response_headers['CST']
                        ~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\requests\structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
           ~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'cst'
2024-04-01 21:12:48,145 - INFO - The input start time: 2024-04-01 19:00:00+00:00
2024-04-01 21:13:21,395 - INFO - The input start time: 2024-04-01 20:00:00+00:00
2024-04-01 21:13:22,222 - ERROR - Internal Server Error: /prices/get-IG-prices/
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\views.py", line 155, in get_IG_prices
    run_IG(ticker_symbol, start_date, end_date)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\run_IG.py", line 158, in run_IG
    ig_service.create_session()
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 393, in create_session
    self._set_headers(response.headers, True)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 450, in _set_headers
    self.CLIENT_TOKEN = response_headers['CST']
                        ~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\requests\structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
           ~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'cst'
2024-04-01 21:13:35,766 - INFO - The input start time: 2024-04-01 19:00:00+00:00
2024-04-01 21:14:51,075 - INFO - Starting scheduler
2024-04-01 21:14:51,076 - INFO - Updater date and time: 2024-04-01 21:14:51.075923
2024-04-01 21:14:51,077 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-04-01 21:14:51,077 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-04-01 21:14:51,077 - INFO - Scheduler started
2024-04-01 21:14:51,079 - INFO - Current time of the scheduler: 2024-04-01 21:14:51.079083
2024-04-01 21:14:51,079 - INFO - Ending scheduler
2024-04-01 21:14:52,088 - INFO - Running job "run_procedure_sequence (trigger: date[2024-04-01 21:14:52 BST], next run at: 2024-04-01 21:14:52 BST)" (scheduled at 2024-04-01 21:14:52.076422+01:00)
2024-04-01 21:14:52,088 - INFO - Removed job e1e6f9b57687433caf6e3178947adf5f
2024-04-01 21:14:52,088 - INFO - Inside the procedure sequence
2024-04-01 21:14:52,088 - INFO - The input start time: 2024-04-01 19:00:00
2024-04-01 21:14:52,687 - ERROR - Job "run_procedure_sequence (trigger: date[2024-04-01 21:14:52 BST], next run at: 2024-04-01 21:14:52 BST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\updater.py", line 71, in run_procedure_sequence
    run_IG(ticker)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\run_IG.py", line 158, in run_IG
    ig_service.create_session()
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 393, in create_session
    self._set_headers(response.headers, True)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 450, in _set_headers
    self.CLIENT_TOKEN = response_headers['CST']
                        ~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\requests\structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
           ~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'cst'
2024-04-01 21:14:53,033 - INFO - Starting scheduler
2024-04-01 21:14:53,033 - INFO - Updater date and time: 2024-04-01 21:14:53.033856
2024-04-01 21:14:53,033 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-04-01 21:14:53,033 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-04-01 21:14:53,033 - INFO - Scheduler started
2024-04-01 21:14:53,033 - INFO - Current time of the scheduler: 2024-04-01 21:14:53.033856
2024-04-01 21:14:53,033 - INFO - Ending scheduler
2024-04-01 21:14:53,060 - INFO - Watching for file changes with StatReloader
2024-04-01 21:14:54,042 - INFO - Running job "run_procedure_sequence (trigger: date[2024-04-01 21:14:54 BST], next run at: 2024-04-01 21:14:54 BST)" (scheduled at 2024-04-01 21:14:54.033856+01:00)
2024-04-01 21:14:54,042 - INFO - Removed job 48940e529ddb4120b8bf5a8d9b40066d
2024-04-01 21:14:54,043 - INFO - Inside the procedure sequence
2024-04-01 21:14:54,046 - INFO - The input start time: 2024-04-01 19:00:00
2024-04-01 21:14:54,243 - WARNING - Not Found: /images/favicon.ico
2024-04-01 21:14:54,721 - ERROR - Job "run_procedure_sequence (trigger: date[2024-04-01 21:14:54 BST], next run at: 2024-04-01 21:14:54 BST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\updater.py", line 71, in run_procedure_sequence
    run_IG(ticker)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\run_IG.py", line 158, in run_IG
    ig_service.create_session()
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 393, in create_session
    self._set_headers(response.headers, True)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 450, in _set_headers
    self.CLIENT_TOKEN = response_headers['CST']
                        ~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\requests\structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
           ~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'cst'
2024-04-01 21:14:56,936 - WARNING - Not Found: /tickers/images/favicon.ico
2024-04-01 21:15:01,583 - WARNING - Not Found: /tickers/ticker/9f53d106-491e-43bc-8f19-f91352ee4426/images/favicon.ico
2024-04-01 21:15:02,676 - WARNING - Not Found: /prices/delete-price/e986dfbe-63aa-4507-8146-b2a14ec95461/images/favicon.ico
2024-04-01 21:15:07,682 - WARNING - Not Found: /prices/delete-price/ce218212-277a-463f-985b-06040f89650c/images/favicon.ico
2024-04-01 21:15:16,786 - INFO - Starting scheduler
2024-04-01 21:15:16,788 - INFO - Updater date and time: 2024-04-01 21:15:16.788405
2024-04-01 21:15:16,789 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-04-01 21:15:16,789 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-04-01 21:15:16,789 - INFO - Scheduler started
2024-04-01 21:15:16,790 - INFO - Current time of the scheduler: 2024-04-01 21:15:16.790904
2024-04-01 21:15:16,791 - INFO - Ending scheduler
2024-04-01 21:15:17,799 - INFO - Running job "run_procedure_sequence (trigger: date[2024-04-01 21:15:17 BST], next run at: 2024-04-01 21:15:17 BST)" (scheduled at 2024-04-01 21:15:17.788405+01:00)
2024-04-01 21:15:17,800 - INFO - Removed job 85715556a58247e1ab13e8816800e011
2024-04-01 21:15:17,800 - INFO - Inside the procedure sequence
2024-04-01 21:15:17,802 - INFO - The input start time: 2024-04-01 19:00:00
2024-04-01 21:15:18,871 - INFO - Starting scheduler
2024-04-01 21:15:18,881 - INFO - Updater date and time: 2024-04-01 21:15:18.881752
2024-04-01 21:15:18,883 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-04-01 21:15:18,883 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-04-01 21:15:18,883 - INFO - Scheduler started
2024-04-01 21:15:18,883 - INFO - Current time of the scheduler: 2024-04-01 21:15:18.883153
2024-04-01 21:15:18,883 - INFO - Ending scheduler
2024-04-01 21:15:18,903 - INFO - Watching for file changes with StatReloader
2024-04-01 21:15:19,886 - INFO - Running job "run_procedure_sequence (trigger: date[2024-04-01 21:15:19 BST], next run at: 2024-04-01 21:15:19 BST)" (scheduled at 2024-04-01 21:15:19.881752+01:00)
2024-04-01 21:15:19,886 - INFO - Removed job 8011c40b72674aecb03c72a4c366c626
2024-04-01 21:15:19,886 - INFO - Inside the procedure sequence
2024-04-01 21:15:19,888 - INFO - The input start time: 2024-04-01 19:00:00
2024-04-01 21:15:20,412 - ERROR - Job "run_procedure_sequence (trigger: date[2024-04-01 21:15:19 BST], next run at: 2024-04-01 21:15:19 BST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\updater.py", line 71, in run_procedure_sequence
    run_IG(ticker)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\run_IG.py", line 158, in run_IG
    ig_service.create_session()
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 393, in create_session
    self._set_headers(response.headers, True)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 450, in _set_headers
    self.CLIENT_TOKEN = response_headers['CST']
                        ~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\requests\structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
           ~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'cst'
2024-04-01 21:15:26,277 - INFO - Job "run_procedure_sequence (trigger: date[2024-04-01 21:15:17 BST], next run at: 2024-04-01 21:15:17 BST)" executed successfully
2024-04-01 21:15:31,265 - WARNING - Not Found: /images/favicon.ico
2024-04-01 21:15:33,840 - WARNING - Not Found: /tickers/images/favicon.ico
2024-04-01 21:15:38,179 - WARNING - Not Found: /tickers/ticker/9f53d106-491e-43bc-8f19-f91352ee4426/images/favicon.ico
2024-04-01 21:19:01,674 - INFO - Starting scheduler
2024-04-01 21:19:01,674 - INFO - Updater date and time: 2024-04-01 21:19:01.674530
2024-04-01 21:19:01,674 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-04-01 21:19:01,674 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-04-01 21:19:01,674 - INFO - Scheduler started
2024-04-01 21:19:01,674 - INFO - Current time of the scheduler: 2024-04-01 21:19:01.674530
2024-04-01 21:19:01,674 - INFO - Ending scheduler
2024-04-01 21:19:03,461 - INFO - Starting scheduler
2024-04-01 21:19:03,461 - INFO - Updater date and time: 2024-04-01 21:19:03.461761
2024-04-01 21:19:03,461 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-04-01 21:19:03,461 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-04-01 21:19:03,461 - INFO - Scheduler started
2024-04-01 21:19:03,477 - INFO - Current time of the scheduler: 2024-04-01 21:19:03.477462
2024-04-01 21:19:03,477 - INFO - Ending scheduler
2024-04-01 21:19:03,477 - INFO - Watching for file changes with StatReloader
2024-04-01 21:19:04,959 - WARNING - Not Found: /images/favicon.ico
2024-04-01 21:19:21,034 - WARNING - Not Found: /ml_models/ml-report/images/favicon.ico
2024-04-01 22:27:29,382 - INFO - Starting scheduler
2024-04-01 22:27:29,382 - INFO - Updater date and time: 2024-04-01 22:27:29.382500
2024-04-01 22:27:29,382 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-04-01 22:27:29,382 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-04-01 22:27:29,382 - INFO - Scheduler started
2024-04-01 22:27:29,382 - INFO - Current time of the scheduler: 2024-04-01 22:27:29.382500
2024-04-01 22:27:29,382 - INFO - Ending scheduler
2024-04-01 22:27:30,397 - INFO - Running job "run_procedure_sequence (trigger: date[2024-04-01 22:27:30 BST], next run at: 2024-04-01 22:27:30 BST)" (scheduled at 2024-04-01 22:27:30.382500+01:00)
2024-04-01 22:27:30,398 - INFO - Removed job c8faf250e08f49b7b2e2a290fb62c193
2024-04-01 22:27:30,398 - INFO - Inside the procedure sequence
2024-04-01 22:27:30,680 - INFO - The input start time: 2024-04-01 21:00:00
2024-04-01 22:27:31,593 - INFO - Starting scheduler
2024-04-01 22:27:31,593 - INFO - Updater date and time: 2024-04-01 22:27:31.593970
2024-04-01 22:27:31,593 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-04-01 22:27:31,593 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-04-01 22:27:31,593 - INFO - Scheduler started
2024-04-01 22:27:31,593 - INFO - Current time of the scheduler: 2024-04-01 22:27:31.593970
2024-04-01 22:27:31,593 - INFO - Ending scheduler
2024-04-01 22:27:31,625 - INFO - Watching for file changes with StatReloader
2024-04-01 22:27:32,612 - INFO - Running job "run_procedure_sequence (trigger: date[2024-04-01 22:27:32 BST], next run at: 2024-04-01 22:27:32 BST)" (scheduled at 2024-04-01 22:27:32.593970+01:00)
2024-04-01 22:27:32,612 - INFO - Removed job 8acdaeee0cfb42919ae1755d51661dea
2024-04-01 22:27:32,612 - INFO - Inside the procedure sequence
2024-04-01 22:27:32,840 - INFO - The input start time: 2024-04-01 21:00:00
2024-04-01 22:27:33,410 - ERROR - Job "run_procedure_sequence (trigger: date[2024-04-01 22:27:32 BST], next run at: 2024-04-01 22:27:32 BST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\updater.py", line 71, in run_procedure_sequence
    run_IG(ticker)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\run_IG.py", line 165, in run_IG
    ig_service.create_session()
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 393, in create_session
    self._set_headers(response.headers, True)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 450, in _set_headers
    self.CLIENT_TOKEN = response_headers['CST']
                        ~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\requests\structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
           ~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'cst'
2024-04-01 22:27:39,177 - INFO - Job "run_procedure_sequence (trigger: date[2024-04-01 22:27:30 BST], next run at: 2024-04-01 22:27:30 BST)" executed successfully
2024-04-06 11:59:25,536 - INFO - Starting scheduler
2024-04-06 11:59:25,536 - INFO - Updater date and time: 2024-04-06 11:59:25.536096
2024-04-06 11:59:25,536 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-04-06 11:59:25,536 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-04-06 11:59:25,536 - INFO - Scheduler started
2024-04-06 11:59:25,536 - INFO - Current time of the scheduler: 2024-04-06 11:59:25.536096
2024-04-06 11:59:25,536 - INFO - Ending scheduler
2024-04-06 11:59:27,139 - INFO - Starting scheduler
2024-04-06 11:59:27,139 - INFO - Updater date and time: 2024-04-06 11:59:27.139705
2024-04-06 11:59:27,139 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-04-06 11:59:27,139 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-04-06 11:59:27,139 - INFO - Scheduler started
2024-04-06 11:59:27,139 - INFO - Current time of the scheduler: 2024-04-06 11:59:27.139705
2024-04-06 11:59:27,139 - INFO - Ending scheduler
2024-04-06 11:59:27,156 - INFO - Watching for file changes with StatReloader
2024-04-06 11:59:29,086 - WARNING - Not Found: /images/favicon.ico
2024-04-06 11:59:36,330 - WARNING - Not Found: /ml_models/ml-report/images/favicon.ico
2024-04-06 12:02:19,107 - INFO - Starting scheduler
2024-04-06 12:02:19,108 - INFO - Updater date and time: 2024-04-06 12:02:19.108812
2024-04-06 12:02:19,108 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-04-06 12:02:19,108 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-04-06 12:02:19,108 - INFO - Scheduler started
2024-04-06 12:02:19,111 - INFO - Current time of the scheduler: 2024-04-06 12:02:19.111308
2024-04-06 12:02:19,111 - INFO - Ending scheduler
2024-04-06 12:02:20,719 - INFO - Starting scheduler
2024-04-06 12:02:20,719 - INFO - Updater date and time: 2024-04-06 12:02:20.719616
2024-04-06 12:02:20,719 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-04-06 12:02:20,719 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-04-06 12:02:20,719 - INFO - Scheduler started
2024-04-06 12:02:20,719 - INFO - Current time of the scheduler: 2024-04-06 12:02:20.719616
2024-04-06 12:02:20,719 - INFO - Ending scheduler
2024-04-06 12:02:20,740 - INFO - Watching for file changes with StatReloader
2024-04-06 12:02:22,157 - WARNING - Not Found: /images/favicon.ico
2024-04-06 12:02:28,523 - WARNING - Not Found: /ml_models/ml-report/images/favicon.ico
2024-04-06 12:05:20,534 - WARNING - Not Found: /images/favicon.ico
2024-04-06 12:05:22,054 - WARNING - Not Found: /ml_models/about/images/favicon.ico
2024-04-06 12:05:23,461 - WARNING - Not Found: /ml_models/about/notes.html
2024-04-06 12:05:23,507 - WARNING - Not Found: /favicon.ico
2024-04-06 12:05:53,180 - WARNING - Not Found: /ml_models/about/notes.html
2024-04-06 12:06:00,007 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-04-06 12:06:00 BST)" (scheduled at 2024-04-06 12:06:00+01:00)
2024-04-06 12:06:00,007 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-04-06 12:06:00 BST)" (scheduled at 2024-04-06 12:06:00+01:00)
2024-04-06 12:06:00,007 - INFO - Inside the procedure sequence
2024-04-06 12:06:00,007 - INFO - Inside the procedure sequence
2024-04-06 12:06:00,226 - INFO - The input start time: 2024-04-06 11:00:00
2024-04-06 12:06:00,226 - INFO - The input start time: 2024-04-06 11:00:00
2024-04-06 12:06:00,239 - ERROR - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-04-06 12:11:00 BST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\urllib3\connection.py", line 203, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\urllib3\util\connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\urllib3\connectionpool.py", line 1096, in _validate_conn
    conn.connect()
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\urllib3\connection.py", line 611, in connect
    self.sock = sock = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\urllib3\connection.py", line 210, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x000001EACA806850>: Failed to resolve 'api.ig.com' ([Errno 11001] getaddrinfo failed)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\urllib3\connectionpool.py", line 844, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.ig.com', port=443): Max retries exceeded with url: /gateway/deal/session (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001EACA806850>: Failed to resolve 'api.ig.com' ([Errno 11001] getaddrinfo failed)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\updater.py", line 71, in run_procedure_sequence
    run_IG(ticker)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\run_IG.py", line 165, in run_IG
    ig_service.create_session()
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 392, in create_session
    response = requests.post(self.BASE_URL  + '/session', data=json.dumps(params), headers=self.BASIC_HEADERS)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.ig.com', port=443): Max retries exceeded with url: /gateway/deal/session (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001EACA806850>: Failed to resolve 'api.ig.com' ([Errno 11001] getaddrinfo failed)"))
2024-04-06 12:06:00,239 - ERROR - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-04-06 12:11:00 BST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\urllib3\connection.py", line 203, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\urllib3\util\connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\urllib3\connectionpool.py", line 1096, in _validate_conn
    conn.connect()
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\urllib3\connection.py", line 611, in connect
    self.sock = sock = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\urllib3\connection.py", line 210, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x000002C96CA42D50>: Failed to resolve 'api.ig.com' ([Errno 11001] getaddrinfo failed)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\urllib3\connectionpool.py", line 844, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.ig.com', port=443): Max retries exceeded with url: /gateway/deal/session (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002C96CA42D50>: Failed to resolve 'api.ig.com' ([Errno 11001] getaddrinfo failed)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\updater.py", line 71, in run_procedure_sequence
    run_IG(ticker)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\run_IG.py", line 165, in run_IG
    ig_service.create_session()
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 392, in create_session
    response = requests.post(self.BASE_URL  + '/session', data=json.dumps(params), headers=self.BASIC_HEADERS)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.ig.com', port=443): Max retries exceeded with url: /gateway/deal/session (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002C96CA42D50>: Failed to resolve 'api.ig.com' ([Errno 11001] getaddrinfo failed)"))
2024-04-06 12:09:28,359 - INFO - C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\urls.py changed, reloading.
2024-04-06 12:09:30,504 - INFO - Starting scheduler
2024-04-06 12:09:30,505 - INFO - Updater date and time: 2024-04-06 12:09:30.505752
2024-04-06 12:09:30,506 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-04-06 12:09:30,506 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-04-06 12:09:30,506 - INFO - Scheduler started
2024-04-06 12:09:30,507 - INFO - Current time of the scheduler: 2024-04-06 12:09:30.507755
2024-04-06 12:09:30,507 - INFO - Ending scheduler
2024-04-06 12:09:30,522 - INFO - Watching for file changes with StatReloader
2024-04-06 12:10:20,115 - INFO - C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py changed, reloading.
2024-04-06 12:10:22,286 - INFO - Starting scheduler
2024-04-06 12:10:22,287 - INFO - Updater date and time: 2024-04-06 12:10:22.287892
2024-04-06 12:10:22,289 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-04-06 12:10:22,289 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-04-06 12:10:22,289 - INFO - Scheduler started
2024-04-06 12:10:22,290 - INFO - Current time of the scheduler: 2024-04-06 12:10:22.290653
2024-04-06 12:10:22,290 - INFO - Ending scheduler
2024-04-06 12:10:22,315 - INFO - Watching for file changes with StatReloader
2024-04-06 12:11:00,002 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-04-06 12:16:00 BST)" (scheduled at 2024-04-06 12:11:00+01:00)
2024-04-06 12:11:00,002 - INFO - Inside the procedure sequence
2024-04-06 12:11:00,003 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-04-06 12:11:00 BST)" (scheduled at 2024-04-06 12:11:00+01:00)
2024-04-06 12:11:00,003 - INFO - Inside the procedure sequence
2024-04-06 12:11:00,012 - INFO - The input start time: 2024-04-06 11:00:00
2024-04-06 12:11:00,263 - INFO - The input start time: 2024-04-06 11:00:00
2024-04-06 12:11:15,246 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-04-06 12:16:00 BST)" executed successfully
2024-04-06 12:11:15,571 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-04-06 12:16:00 BST)" executed successfully
2024-04-06 12:11:38,922 - INFO - Starting scheduler
2024-04-06 12:11:38,922 - INFO - Updater date and time: 2024-04-06 12:11:38.922981
2024-04-06 12:11:38,922 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-04-06 12:11:38,922 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-04-06 12:11:38,922 - INFO - Scheduler started
2024-04-06 12:11:38,922 - INFO - Current time of the scheduler: 2024-04-06 12:11:38.922981
2024-04-06 12:11:38,922 - INFO - Ending scheduler
2024-04-06 12:11:43,833 - INFO - Starting scheduler
2024-04-06 12:11:43,834 - INFO - Updater date and time: 2024-04-06 12:11:43.833567
2024-04-06 12:11:43,835 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-04-06 12:11:43,835 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-04-06 12:11:43,835 - INFO - Scheduler started
2024-04-06 12:11:43,836 - INFO - Current time of the scheduler: 2024-04-06 12:11:43.836583
2024-04-06 12:11:43,836 - INFO - Ending scheduler
2024-04-06 12:11:45,528 - INFO - Starting scheduler
2024-04-06 12:11:45,528 - INFO - Updater date and time: 2024-04-06 12:11:45.528022
2024-04-06 12:11:45,528 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-04-06 12:11:45,528 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-04-06 12:11:45,528 - INFO - Scheduler started
2024-04-06 12:11:45,528 - INFO - Current time of the scheduler: 2024-04-06 12:11:45.528022
2024-04-06 12:11:45,528 - INFO - Ending scheduler
2024-04-06 12:11:45,558 - INFO - Watching for file changes with StatReloader
2024-04-06 12:11:58,479 - INFO - C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py changed, reloading.
2024-04-06 12:12:00,659 - INFO - Starting scheduler
2024-04-06 12:12:00,659 - INFO - Updater date and time: 2024-04-06 12:12:00.659302
2024-04-06 12:12:00,659 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-04-06 12:12:00,659 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-04-06 12:12:00,659 - INFO - Scheduler started
2024-04-06 12:12:00,659 - INFO - Current time of the scheduler: 2024-04-06 12:12:00.659302
2024-04-06 12:12:00,659 - INFO - Ending scheduler
2024-04-06 12:12:00,678 - INFO - Watching for file changes with StatReloader
2024-04-06 12:12:05,862 - ERROR - Internal Server Error: /ml_models/notes/
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py", line 487, in notes
    return render(request, 'notes.html')
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: notes.html
2024-04-06 12:13:03,951 - INFO - C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py changed, reloading.
2024-04-06 12:13:06,057 - INFO - Starting scheduler
2024-04-06 12:13:06,057 - INFO - Updater date and time: 2024-04-06 12:13:06.057929
2024-04-06 12:13:06,057 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-04-06 12:13:06,057 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-04-06 12:13:06,057 - INFO - Scheduler started
2024-04-06 12:13:06,057 - INFO - Current time of the scheduler: 2024-04-06 12:13:06.057929
2024-04-06 12:13:06,057 - INFO - Ending scheduler
2024-04-06 12:13:06,087 - INFO - Watching for file changes with StatReloader
2024-04-06 12:13:07,462 - WARNING - Not Found: /ml_models/notes/images/favicon.ico
2024-04-06 12:16:00,002 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-04-06 12:16:00 BST)" (scheduled at 2024-04-06 12:16:00+01:00)
2024-04-06 12:16:00,003 - INFO - Inside the procedure sequence
2024-04-06 12:16:00,012 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-04-06 12:16:00 BST)" (scheduled at 2024-04-06 12:16:00+01:00)
2024-04-06 12:16:00,012 - INFO - Inside the procedure sequence
2024-04-06 12:16:00,183 - INFO - The input start time: 2024-04-06 11:00:00
2024-04-06 12:16:00,184 - INFO - The input start time: 2024-04-06 11:00:00
2024-04-06 12:16:08,760 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-04-06 12:21:00 BST)" executed successfully
2024-04-06 12:16:09,139 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-04-06 12:21:00 BST)" executed successfully
2024-04-06 12:21:00,008 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-04-06 12:26:00 BST)" (scheduled at 2024-04-06 12:21:00+01:00)
2024-04-06 12:21:00,008 - INFO - Inside the procedure sequence
2024-04-06 12:21:00,008 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-04-06 12:26:00 BST)" (scheduled at 2024-04-06 12:21:00+01:00)
2024-04-06 12:21:00,008 - INFO - Inside the procedure sequence
2024-04-06 12:21:00,013 - INFO - The input start time: 2024-04-06 11:00:00
2024-04-06 12:21:00,013 - INFO - The input start time: 2024-04-06 11:00:00
2024-04-06 12:21:00,729 - ERROR - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-04-06 12:26:00 BST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\updater.py", line 71, in run_procedure_sequence
    run_IG(ticker)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\run_IG.py", line 165, in run_IG
    ig_service.create_session()
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 393, in create_session
    self._set_headers(response.headers, True)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 450, in _set_headers
    self.CLIENT_TOKEN = response_headers['CST']
                        ~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\requests\structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
           ~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'cst'
2024-04-06 12:21:07,864 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-04-06 12:26:00 BST)" executed successfully
2024-04-06 12:25:53,210 - INFO - Starting scheduler
2024-04-06 12:25:53,210 - INFO - Updater date and time: 2024-04-06 12:25:53.210958
2024-04-06 12:25:53,210 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-04-06 12:25:53,210 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-04-06 12:25:53,210 - INFO - Scheduler started
2024-04-06 12:25:53,210 - INFO - Current time of the scheduler: 2024-04-06 12:25:53.210958
2024-04-06 12:25:53,210 - INFO - Ending scheduler
2024-04-06 12:25:55,045 - INFO - Starting scheduler
2024-04-06 12:25:55,045 - INFO - Updater date and time: 2024-04-06 12:25:55.045999
2024-04-06 12:25:55,047 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-04-06 12:25:55,047 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-04-06 12:25:55,047 - INFO - Scheduler started
2024-04-06 12:25:55,048 - INFO - Current time of the scheduler: 2024-04-06 12:25:55.048019
2024-04-06 12:25:55,048 - INFO - Ending scheduler
2024-04-06 12:25:55,067 - INFO - Watching for file changes with StatReloader
2024-04-06 12:26:00,002 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-04-06 12:31:00 BST)" (scheduled at 2024-04-06 12:26:00+01:00)
2024-04-06 12:26:00,003 - INFO - Inside the procedure sequence
2024-04-06 12:26:00,018 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-04-06 12:26:00 BST)" (scheduled at 2024-04-06 12:26:00+01:00)
2024-04-06 12:26:00,018 - INFO - Inside the procedure sequence
2024-04-06 12:26:00,159 - INFO - The input start time: 2024-04-06 11:00:00
2024-04-06 12:26:00,170 - INFO - The input start time: 2024-04-06 11:00:00
2024-04-06 12:26:03,873 - WARNING - Not Found: /ml_models/model-accuracy/images/favicon.ico
2024-04-06 12:26:11,523 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-04-06 12:31:00 BST)" executed successfully
2024-04-06 12:26:12,926 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-04-06 12:31:00 BST)" executed successfully
2024-04-14 10:16:45,972 - INFO - Starting scheduler
2024-04-14 10:16:45,973 - INFO - Updater date and time: 2024-04-14 10:16:45.972685
2024-04-14 10:16:45,973 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-04-14 10:16:45,973 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-04-14 10:16:45,973 - INFO - Scheduler started
2024-04-14 10:16:45,974 - INFO - Current time of the scheduler: 2024-04-14 10:16:45.974687
2024-04-14 10:16:45,974 - INFO - Ending scheduler
2024-04-14 10:16:47,819 - INFO - Starting scheduler
2024-04-14 10:16:47,819 - INFO - Updater date and time: 2024-04-14 10:16:47.819767
2024-04-14 10:16:47,820 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-04-14 10:16:47,821 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-04-14 10:16:47,821 - INFO - Scheduler started
2024-04-14 10:16:47,821 - INFO - Current time of the scheduler: 2024-04-14 10:16:47.821774
2024-04-14 10:16:47,822 - INFO - Ending scheduler
2024-04-14 10:16:47,838 - INFO - Watching for file changes with StatReloader
2024-04-14 10:18:29,591 - INFO - Starting scheduler
2024-04-14 10:18:29,592 - INFO - Updater date and time: 2024-04-14 10:18:29.592010
2024-04-14 10:18:29,592 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-04-14 10:18:29,593 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-04-14 10:18:29,593 - INFO - Scheduler started
2024-04-14 10:18:29,593 - INFO - Current time of the scheduler: 2024-04-14 10:18:29.593931
2024-04-14 10:18:29,593 - INFO - Ending scheduler
2024-04-14 10:18:31,410 - INFO - Starting scheduler
2024-04-14 10:18:31,411 - INFO - Updater date and time: 2024-04-14 10:18:31.411843
2024-04-14 10:18:31,412 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-04-14 10:18:31,412 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-04-14 10:18:31,412 - INFO - Scheduler started
2024-04-14 10:18:31,413 - INFO - Current time of the scheduler: 2024-04-14 10:18:31.413845
2024-04-14 10:18:31,413 - INFO - Ending scheduler
2024-04-14 10:18:31,429 - INFO - Watching for file changes with StatReloader
2024-04-14 10:20:25,797 - INFO - C:\Users\sunny\Desktop\Development\python\TradePro\env.py changed, reloading.
2024-04-14 10:20:27,816 - INFO - Starting scheduler
2024-04-14 10:20:27,817 - INFO - Updater date and time: 2024-04-14 10:20:27.817115
2024-04-14 10:20:27,818 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-04-14 10:20:27,818 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-04-14 10:20:27,818 - INFO - Scheduler started
2024-04-14 10:20:27,819 - INFO - Current time of the scheduler: 2024-04-14 10:20:27.819097
2024-04-14 10:20:27,819 - INFO - Ending scheduler
2024-04-14 10:20:27,836 - INFO - Watching for file changes with StatReloader
2024-04-14 10:20:42,112 - INFO - Starting scheduler
2024-04-14 10:20:42,113 - INFO - Updater date and time: 2024-04-14 10:20:42.113409
2024-04-14 10:20:42,114 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-04-14 10:20:42,114 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-04-14 10:20:42,114 - INFO - Scheduler started
2024-04-14 10:20:42,115 - INFO - Current time of the scheduler: 2024-04-14 10:20:42.115492
2024-04-14 10:20:42,115 - INFO - Ending scheduler
2024-04-14 10:20:44,038 - INFO - Starting scheduler
2024-04-14 10:20:44,039 - INFO - Updater date and time: 2024-04-14 10:20:44.038589
2024-04-14 10:20:44,040 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-04-14 10:20:44,040 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-04-14 10:20:44,040 - INFO - Scheduler started
2024-04-14 10:20:44,041 - INFO - Current time of the scheduler: 2024-04-14 10:20:44.041589
2024-04-14 10:20:44,041 - INFO - Ending scheduler
2024-04-14 10:20:44,056 - INFO - Watching for file changes with StatReloader
2024-04-14 10:21:00,005 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-04-14 10:21:00 BST)" (scheduled at 2024-04-14 10:21:00+01:00)
2024-04-14 10:21:00,005 - INFO - Inside the procedure sequence
2024-04-14 10:21:00,005 - INFO - Inside the procedure sequence
2024-04-14 10:21:00,217 - INFO - The input start time: 2024-04-14 09:00:00
2024-04-14 10:21:00,217 - INFO - The input start time: 2024-04-14 09:00:00
2024-04-14 10:21:01,004 - ERROR - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-04-14 10:26:00 BST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\updater.py", line 71, in run_procedure_sequence
    run_IG(ticker)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\run_IG.py", line 165, in run_IG
    ig_service.create_session()
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 393, in create_session
    self._set_headers(response.headers, True)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 450, in _set_headers
    self.CLIENT_TOKEN = response_headers['CST']
                        ~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\requests\structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
           ~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'cst'
2024-04-14 10:21:09,206 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-04-14 10:26:00 BST)" executed successfully
2024-04-14 10:24:15,590 - INFO - Starting scheduler
2024-04-14 10:24:15,591 - INFO - Updater date and time: 2024-04-14 10:24:15.591304
2024-04-14 10:24:15,592 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-04-14 10:24:15,592 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-04-14 10:24:15,592 - INFO - Scheduler started
2024-04-14 10:24:15,593 - INFO - Current time of the scheduler: 2024-04-14 10:24:15.593306
2024-04-14 10:24:15,593 - INFO - Ending scheduler
2024-04-14 10:24:17,399 - INFO - Starting scheduler
2024-04-14 10:24:17,400 - INFO - Updater date and time: 2024-04-14 10:24:17.400534
2024-04-14 10:24:17,401 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-04-14 10:24:17,401 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-04-14 10:24:17,401 - INFO - Scheduler started
2024-04-14 10:24:17,402 - INFO - Current time of the scheduler: 2024-04-14 10:24:17.402534
2024-04-14 10:24:17,402 - INFO - Ending scheduler
2024-04-14 10:24:17,418 - INFO - Watching for file changes with StatReloader
2024-04-14 10:24:18,702 - WARNING - Not Found: /images/favicon.ico
2024-04-14 10:26:00,003 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-04-14 10:26:00 BST)" (scheduled at 2024-04-14 10:26:00+01:00)
2024-04-14 10:26:00,003 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-04-14 10:26:00 BST)" (scheduled at 2024-04-14 10:26:00+01:00)
2024-04-14 10:26:00,004 - INFO - Inside the procedure sequence
2024-04-14 10:26:00,004 - INFO - Inside the procedure sequence
2024-04-14 10:26:00,171 - INFO - The input start time: 2024-04-14 09:00:00
2024-04-14 10:26:00,173 - INFO - The input start time: 2024-04-14 09:00:00
2024-04-14 10:26:11,178 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-04-14 10:31:00 BST)" executed successfully
2024-04-14 10:26:11,580 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-04-14 10:31:00 BST)" executed successfully
2024-04-14 10:31:00,013 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-04-14 10:36:00 BST)" (scheduled at 2024-04-14 10:31:00+01:00)
2024-04-14 10:31:00,014 - INFO - Inside the procedure sequence
2024-04-14 10:31:00,014 - INFO - Inside the procedure sequence
2024-04-14 10:31:00,018 - INFO - The input start time: 2024-04-14 09:00:00
2024-04-14 10:31:00,018 - INFO - The input start time: 2024-04-14 09:00:00
2024-04-14 10:31:11,282 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-04-14 10:36:00 BST)" executed successfully
2024-04-14 10:31:11,802 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-04-14 10:36:00 BST)" executed successfully
