2024-08-01 19:17:18,289 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-01 19:17:18,289 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-01 19:17:18,289 - INFO - Scheduler started
2024-08-01 19:17:20,542 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-01 19:17:20,542 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-01 19:17:20,542 - INFO - Scheduler started
2024-08-01 19:17:20,561 - INFO - Watching for file changes with StatReloader
2024-08-01 19:17:39,457 - WARNING - Not Found: /ml_models/ml-report/images/favicon.ico
2024-08-01 19:25:47,027 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-01 19:25:47,028 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-01 19:25:47,028 - INFO - Scheduler started
2024-08-01 19:25:49,478 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-01 19:25:49,478 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-01 19:25:49,478 - INFO - Scheduler started
2024-08-01 19:25:49,498 - INFO - Watching for file changes with StatReloader
2024-08-01 19:25:59,055 - ERROR - Internal Server Error: /ml_models/ml-report/
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py", line 465, in ml_report2
    pred_var_pos, pred_var_neg = variability_analysis(model_ticker, 0.1)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\trade_model.py", line 473, in variability_analysis
    X_live_variability = dp.prediction_variability(sensitivity_adjustment)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\price_processing.py", line 694, in prediction_variability
    variability_df_pos = self.stats_df_gen(variability_df,2)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\price_processing.py", line 587, in stats_df_gen
    merged_df.to_csv(r"C:\Users\sunny\Desktop\Development\before_df-1.csv", index=False)
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\pandas\core\generic.py", line 3466, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\pandas\io\formats\format.py", line 1105, in to_csv
    csv_formatter.save()
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\pandas\io\formats\csvs.py", line 237, in save
    with get_handle(
         ^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\pandas\io\common.py", line 702, in get_handle
    handle = open(
             ^^^^^
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\sunny\\Desktop\\Development\\before_df-1.csv'
2024-08-01 19:26:00,008 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-01 19:26:00 BST)" (scheduled at 2024-08-01 19:26:00+01:00)
2024-08-01 19:26:00,008 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-01 19:26:00 BST)" (scheduled at 2024-08-01 19:26:00+01:00)
2024-08-01 19:26:00,198 - INFO - The input start time: 2024-08-01 18:00:00
2024-08-01 19:26:00,198 - INFO - The input start time: 2024-08-01 18:00:00
2024-08-01 19:26:15,558 - ERROR - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-01 19:31:00 BST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\updater.py", line 74, in run_procedure_sequence
    comparison_comment, general_ticker_info, send_email_enabled = run_model_predictions(ticker)
                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\trade_model.py", line 420, in run_model_predictions
    pred_reverse_1h_v5, pred_continue_1h_v5, pred_historical_1h_v5, _ = standard_analysis(model_ticker, "1h_v5")
                                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\trade_model.py", line 214, in standard_analysis
    X_live_reverse = dp.scenario_reverse()
                     ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\price_processing.py", line 614, in scenario_reverse
    reverse_df_2pips = self.stats_df_gen(df, 2)
                       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\price_processing.py", line 587, in stats_df_gen
    merged_df.to_csv(r"C:\Users\sunny\Desktop\Development\before_df-1.csv", index=False)
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\pandas\core\generic.py", line 3466, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\pandas\io\formats\format.py", line 1105, in to_csv
    csv_formatter.save()
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\pandas\io\formats\csvs.py", line 237, in save
    with get_handle(
         ^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\pandas\io\common.py", line 702, in get_handle
    handle = open(
             ^^^^^
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\sunny\\Desktop\\Development\\before_df-1.csv'
2024-08-01 19:26:15,864 - ERROR - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-01 19:31:00 BST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\updater.py", line 74, in run_procedure_sequence
    comparison_comment, general_ticker_info, send_email_enabled = run_model_predictions(ticker)
                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\trade_model.py", line 420, in run_model_predictions
    pred_reverse_1h_v5, pred_continue_1h_v5, pred_historical_1h_v5, _ = standard_analysis(model_ticker, "1h_v5")
                                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\trade_model.py", line 214, in standard_analysis
    X_live_reverse = dp.scenario_reverse()
                     ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\price_processing.py", line 614, in scenario_reverse
    reverse_df_2pips = self.stats_df_gen(df, 2)
                       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\price_processing.py", line 587, in stats_df_gen
    merged_df.to_csv(r"C:\Users\sunny\Desktop\Development\before_df-1.csv", index=False)
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\pandas\core\generic.py", line 3466, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\pandas\io\formats\format.py", line 1105, in to_csv
    csv_formatter.save()
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\pandas\io\formats\csvs.py", line 237, in save
    with get_handle(
         ^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\pandas\io\common.py", line 702, in get_handle
    handle = open(
             ^^^^^
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\sunny\\Desktop\\Development\\before_df-1.csv'
2024-08-01 19:26:55,383 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-01 19:26:55,384 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-01 19:26:55,384 - INFO - Scheduler started
2024-08-01 19:26:57,633 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-01 19:26:57,633 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-01 19:26:57,633 - INFO - Scheduler started
2024-08-01 19:26:57,656 - INFO - Watching for file changes with StatReloader
2024-08-01 19:43:23,360 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-01 19:43:23,360 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-01 19:43:23,360 - INFO - Scheduler started
2024-08-01 19:43:25,616 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-01 19:43:25,617 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-01 19:43:25,617 - INFO - Scheduler started
2024-08-01 19:43:25,634 - INFO - Watching for file changes with StatReloader
2024-08-01 19:43:33,063 - WARNING - Not Found: /tickers/images/favicon.ico
2024-08-01 19:43:38,753 - WARNING - Not Found: /prices/get-IG-prices/images/favicon.ico
2024-08-01 19:44:04,607 - INFO - The input start time: 2024-07-29 13:00:00+00:00
2024-08-01 19:44:10,946 - WARNING - Not Found: /tickers/ticker/9f53d106-491e-43bc-8f19-f91352ee4426/images/favicon.ico
2024-08-01 19:44:19,873 - ERROR - Internal Server Error: /ml_models/ml-report/
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py", line 465, in ml_report2
    pred_var_pos, pred_var_neg = variability_analysis(model_ticker, 0.1)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\trade_model.py", line 473, in variability_analysis
    X_live_variability = dp.prediction_variability(sensitivity_adjustment)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\price_processing.py", line 694, in prediction_variability
    variability_df_pos = self.stats_df_gen(variability_df,2)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\price_processing.py", line 584, in stats_df_gen
    df.to_csv(r"C:\Users\sunny\Desktop\Development\df-1.csv", index=False)
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\pandas\core\generic.py", line 3466, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\pandas\io\formats\format.py", line 1105, in to_csv
    csv_formatter.save()
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\pandas\io\formats\csvs.py", line 237, in save
    with get_handle(
         ^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\pandas\io\common.py", line 702, in get_handle
    handle = open(
             ^^^^^
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\sunny\\Desktop\\Development\\df-1.csv'
2024-08-01 19:51:48,096 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-01 19:51:48,097 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-01 19:51:48,097 - INFO - Scheduler started
2024-08-01 19:51:50,411 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-01 19:51:50,411 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-01 19:51:50,411 - INFO - Scheduler started
2024-08-01 19:51:50,430 - INFO - Watching for file changes with StatReloader
2024-08-01 19:58:11,271 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-01 19:58:11,271 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-01 19:58:11,271 - INFO - Scheduler started
2024-08-01 19:58:13,417 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-01 19:58:13,417 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-01 19:58:13,417 - INFO - Scheduler started
2024-08-01 19:58:13,435 - INFO - Watching for file changes with StatReloader
2024-08-01 20:02:32,172 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-01 20:02:32,172 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-01 20:02:32,172 - INFO - Scheduler started
2024-08-01 20:02:34,365 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-01 20:02:34,365 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-01 20:02:34,365 - INFO - Scheduler started
2024-08-01 20:02:34,385 - INFO - Watching for file changes with StatReloader
2024-08-01 20:02:42,145 - WARNING - Not Found: /news/get-news/images/favicon.ico
2024-08-01 20:08:08,065 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-01 20:08:08,065 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-01 20:08:08,065 - INFO - Scheduler started
2024-08-01 20:08:10,180 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-01 20:08:10,180 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-01 20:08:10,180 - INFO - Scheduler started
2024-08-01 20:08:10,199 - INFO - Watching for file changes with StatReloader
2024-08-01 20:11:09,344 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-01 20:11:09,344 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-01 20:11:09,344 - INFO - Scheduler started
2024-08-01 20:11:11,589 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-01 20:11:11,589 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-01 20:11:11,589 - INFO - Scheduler started
2024-08-01 20:11:11,608 - INFO - Watching for file changes with StatReloader
2024-08-01 20:11:18,105 - ERROR - Internal Server Error: /news/get-news/
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\news\views.py", line 106, in get_news
    return render(request, 'news/get_news.html', {'news_data': news_data, 'form': form})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\template\defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'news/upload-news.html' not found. 'news/upload-news.html' is not a valid view function or pattern name.
2024-08-01 20:12:49,585 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-01 20:12:49,586 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-01 20:12:49,586 - INFO - Scheduler started
2024-08-01 20:12:51,766 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-01 20:12:51,766 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-01 20:12:51,766 - INFO - Scheduler started
2024-08-01 20:12:51,783 - INFO - Watching for file changes with StatReloader
2024-08-01 20:12:57,633 - WARNING - Not Found: /news/upload-news/images/favicon.ico
2024-08-01 20:14:04,644 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-01 20:14:04,644 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-01 20:14:04,644 - INFO - Scheduler started
2024-08-01 20:14:06,835 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-01 20:14:06,836 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-01 20:14:06,836 - INFO - Scheduler started
2024-08-01 20:14:06,854 - INFO - Watching for file changes with StatReloader
2024-08-01 20:49:52,259 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-01 20:49:52,259 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-01 20:49:52,259 - INFO - Scheduler started
2024-08-01 20:49:54,743 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-01 20:49:54,743 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-01 20:49:54,743 - INFO - Scheduler started
2024-08-01 20:49:54,764 - INFO - Watching for file changes with StatReloader
2024-08-01 22:05:58,329 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-01 22:05:58,330 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-01 22:05:58,330 - INFO - Scheduler started
2024-08-01 22:06:00,003 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-01 22:06:00 BST)" (scheduled at 2024-08-01 22:06:00+01:00)
2024-08-01 22:06:00,142 - INFO - The input start time: 2024-08-01 21:00:00
2024-08-01 22:06:00,705 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-01 22:06:00,705 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-01 22:06:00,705 - INFO - Scheduler started
2024-08-01 22:06:00,722 - INFO - Watching for file changes with StatReloader
2024-08-01 22:06:15,864 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-01 22:11:00 BST)" executed successfully
2024-08-01 22:06:40,105 - ERROR - Internal Server Error: /ml_models/ml-news-model/
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py", line 681, in ml_news_model
    return render(request, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\template\loaders\base.py", line 17, in get_template
    for origin in self.get_template_sources(template_name):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\template\loaders\cached.py", line 70, in get_template_sources
    yield from loader.get_template_sources(template_name)
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\template\loaders\filesystem.py", line 35, in get_template_sources
    name = safe_join(template_dir, template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\utils\_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
                         ^^^^^^^^^^^^^^^^^^
  File "<frozen ntpath>", line 147, in join
  File "<frozen genericpath>", line 152, in _check_arg_types
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'dict'
2024-08-01 22:13:33,238 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-01 22:13:33,238 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-01 22:13:33,238 - INFO - Scheduler started
2024-08-01 22:13:35,569 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-01 22:13:35,569 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-01 22:13:35,569 - INFO - Scheduler started
2024-08-01 22:13:35,588 - INFO - Watching for file changes with StatReloader
2024-08-01 22:13:50,055 - ERROR - Internal Server Error: /ml_models/ml-news-model/
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py", line 681, in ml_news_model
    return render(request, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\template\loaders\base.py", line 17, in get_template
    for origin in self.get_template_sources(template_name):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\template\loaders\cached.py", line 70, in get_template_sources
    yield from loader.get_template_sources(template_name)
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\template\loaders\filesystem.py", line 35, in get_template_sources
    name = safe_join(template_dir, template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\utils\_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
                         ^^^^^^^^^^^^^^^^^^
  File "<frozen ntpath>", line 147, in join
  File "<frozen genericpath>", line 152, in _check_arg_types
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'dict'
2024-08-01 22:15:07,566 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-01 22:15:07,566 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-01 22:15:07,566 - INFO - Scheduler started
2024-08-01 22:15:09,962 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-01 22:15:09,962 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-01 22:15:09,962 - INFO - Scheduler started
2024-08-01 22:15:09,983 - INFO - Watching for file changes with StatReloader
2024-08-01 22:23:20,171 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-01 22:23:20,172 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-01 22:23:20,172 - INFO - Scheduler started
2024-08-01 22:23:22,442 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-01 22:23:22,443 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-01 22:23:22,443 - INFO - Scheduler started
2024-08-01 22:23:22,461 - INFO - Watching for file changes with StatReloader
2024-08-01 22:23:35,595 - WARNING - Not Found: /ml_models/ml-news-model/images/favicon.ico
2024-08-01 22:23:39,025 - ERROR - Internal Server Error: /ml_models/ml-news-model/
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py", line 660, in ml_news_model
    news_pred_results = news_model_run(ticker_input, user_input, model_version)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\news_model.py", line 73, in news_model_run
    model_prediction = model_pipeline.predict(X_live_subset)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\sklearn\pipeline.py", line 515, in predict
    return self.steps[-1][1].predict(Xt, **predict_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\sklearn\ensemble\_gb.py", line 1293, in predict
    raw_predictions = self.decision_function(X)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\sklearn\ensemble\_gb.py", line 1246, in decision_function
    X = self._validate_data(
        ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\sklearn\base.py", line 605, in _validate_data
    out = check_array(X, input_name="X", **check_params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\sklearn\utils\validation.py", line 957, in check_array
    _assert_all_finite(
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\sklearn\utils\validation.py", line 122, in _assert_all_finite
    _assert_all_finite_element_wise(
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\sklearn\utils\validation.py", line 171, in _assert_all_finite_element_wise
    raise ValueError(msg_err)
ValueError: Input X contains NaN.
GradientBoostingClassifier does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values
2024-08-01 22:26:10,072 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-01 22:26:10,073 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-01 22:26:10,073 - INFO - Scheduler started
2024-08-01 22:26:12,472 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-01 22:26:12,472 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-01 22:26:12,472 - INFO - Scheduler started
2024-08-01 22:26:12,493 - INFO - Watching for file changes with StatReloader
2024-08-01 22:31:15,185 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-01 22:31:15,185 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-01 22:31:15,185 - INFO - Scheduler started
2024-08-01 22:31:17,402 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-01 22:31:17,403 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-01 22:31:17,403 - INFO - Scheduler started
2024-08-01 22:31:17,421 - INFO - Watching for file changes with StatReloader
2024-08-01 22:36:00,010 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-01 22:41:00 BST)" (scheduled at 2024-08-01 22:36:00+01:00)
2024-08-01 22:36:00,011 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-01 22:36:00 BST)" (scheduled at 2024-08-01 22:36:00+01:00)
2024-08-01 22:36:00,171 - INFO - The input start time: 2024-08-01 21:00:00
2024-08-01 22:36:00,171 - INFO - The input start time: 2024-08-01 21:00:00
2024-08-01 22:36:22,626 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-01 22:41:00 BST)" executed successfully
2024-08-01 22:36:25,280 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-01 22:41:00 BST)" executed successfully
2024-08-03 07:49:59,165 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-03 07:49:59,165 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-03 07:49:59,165 - INFO - Scheduler started
2024-08-03 07:50:01,466 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-03 07:50:01,467 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-03 07:50:01,467 - INFO - Scheduler started
2024-08-03 07:50:01,484 - INFO - Watching for file changes with StatReloader
2024-08-03 07:50:03,363 - WARNING - Not Found: /images/favicon.ico
2024-08-03 07:50:05,121 - WARNING - Not Found: /news/get-news/images/favicon.ico
2024-08-03 07:50:06,455 - WARNING - Not Found: /news/upload-news/images/favicon.ico
2024-08-03 07:51:00,010 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-03 07:51:00 BST)" (scheduled at 2024-08-03 07:51:00+01:00)
2024-08-03 07:51:00,011 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-03 07:51:00 BST)" (scheduled at 2024-08-03 07:51:00+01:00)
2024-08-03 07:51:00,246 - INFO - The input start time: 2024-08-03 06:00:00
2024-08-03 07:51:00,246 - INFO - The input start time: 2024-08-03 06:00:00
2024-08-03 07:51:21,108 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-03 07:56:00 BST)" executed successfully
2024-08-03 07:51:22,786 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-03 07:56:00 BST)" executed successfully
2024-08-03 12:45:19,521 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-03 12:45:19,522 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-03 12:45:19,522 - INFO - Scheduler started
2024-08-03 12:45:21,858 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-03 12:45:21,858 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-03 12:45:21,858 - INFO - Scheduler started
2024-08-03 12:45:21,882 - INFO - Watching for file changes with StatReloader
2024-08-03 12:45:24,340 - WARNING - Not Found: /images/favicon.ico
2024-08-03 12:45:26,410 - WARNING - Not Found: /ml_models/about/images/favicon.ico
2024-08-03 12:45:30,850 - WARNING - Not Found: /login/images/favicon.ico
2024-08-03 12:45:46,140 - WARNING - Not Found: /account/images/favicon.ico
2024-08-03 12:45:48,677 - WARNING - Not Found: /profile/images/favicon.ico
2024-08-03 12:45:52,692 - WARNING - Not Found: /ml_models/ml-variability/images/favicon.ico
2024-08-03 12:45:53,769 - WARNING - Not Found: /users-list/images/favicon.ico
2024-08-03 12:46:00,014 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-03 12:46:00 BST)" (scheduled at 2024-08-03 12:46:00+01:00)
2024-08-03 12:46:00,014 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-03 12:46:00 BST)" (scheduled at 2024-08-03 12:46:00+01:00)
2024-08-03 12:46:00,244 - INFO - The input start time: 2024-08-03 11:00:00
2024-08-03 12:46:00,244 - INFO - The input start time: 2024-08-03 11:00:00
2024-08-03 12:46:22,037 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-03 12:51:00 BST)" executed successfully
2024-08-03 12:46:23,132 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-03 12:51:00 BST)" executed successfully
2024-08-03 13:00:21,296 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-03 13:00:21,296 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-03 13:00:21,296 - INFO - Scheduler started
2024-08-03 13:00:23,681 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-03 13:00:23,681 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-03 13:00:23,681 - INFO - Scheduler started
2024-08-03 13:00:23,700 - INFO - Watching for file changes with StatReloader
2024-08-03 13:00:36,411 - WARNING - Not Found: /tickers/images/favicon.ico
2024-08-03 13:01:00,015 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-03 13:01:00 BST)" (scheduled at 2024-08-03 13:01:00+01:00)
2024-08-03 13:01:00,015 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-03 13:01:00 BST)" (scheduled at 2024-08-03 13:01:00+01:00)
2024-08-03 13:01:00,168 - INFO - The input start time: 2024-08-03 12:00:00
2024-08-03 13:01:00,170 - INFO - The input start time: 2024-08-03 12:00:00
2024-08-03 13:01:01,792 - ERROR - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-03 13:06:00 BST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\updater.py", line 73, in run_procedure_sequence
    run_IG(ticker)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\run_IG.py", line 165, in run_IG
    ig_service.create_session()
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 393, in create_session
    self._set_headers(response.headers, True)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 450, in _set_headers
    self.CLIENT_TOKEN = response_headers['CST']
                        ~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\requests\structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
           ~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'cst'
2024-08-03 13:01:01,792 - ERROR - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-03 13:06:00 BST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\updater.py", line 73, in run_procedure_sequence
    run_IG(ticker)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\run_IG.py", line 165, in run_IG
    ig_service.create_session()
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 393, in create_session
    self._set_headers(response.headers, True)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 450, in _set_headers
    self.CLIENT_TOKEN = response_headers['CST']
                        ~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\requests\structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
           ~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'cst'
2024-08-03 13:01:06,138 - WARNING - Not Found: /users/backend-control
2024-08-03 13:01:06,188 - WARNING - Not Found: /favicon.ico
2024-08-03 13:02:26,884 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-03 13:02:26,885 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-03 13:02:26,885 - INFO - Scheduler started
2024-08-03 13:02:28,997 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-03 13:02:28,998 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-03 13:02:28,998 - INFO - Scheduler started
2024-08-03 13:02:29,018 - INFO - Watching for file changes with StatReloader
2024-08-03 13:03:16,913 - ERROR - Internal Server Error: /ml_models/delete-file/logfile.log/
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py", line 732, in delete_file
    os.remove(file_path)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\sunny\\Desktop\\Development\\python\\TradePro\\media\\model_results\\logfile.log'
2024-08-03 13:03:26,510 - WARNING - Not Found: /ml_models/notes/images/favicon.ico
2024-08-03 13:06:00,012 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-03 13:06:00 BST)" (scheduled at 2024-08-03 13:06:00+01:00)
2024-08-03 13:06:00,012 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-03 13:06:00 BST)" (scheduled at 2024-08-03 13:06:00+01:00)
2024-08-03 13:06:00,155 - INFO - The input start time: 2024-08-03 12:00:00
2024-08-03 13:06:00,155 - INFO - The input start time: 2024-08-03 12:00:00
2024-08-03 13:06:00,981 - ERROR - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-03 13:11:00 BST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\updater.py", line 73, in run_procedure_sequence
    run_IG(ticker)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\run_IG.py", line 165, in run_IG
    ig_service.create_session()
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 393, in create_session
    self._set_headers(response.headers, True)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 450, in _set_headers
    self.CLIENT_TOKEN = response_headers['CST']
                        ~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\requests\structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
           ~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'cst'
2024-08-03 13:06:00,982 - ERROR - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-03 13:11:00 BST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\updater.py", line 73, in run_procedure_sequence
    run_IG(ticker)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\run_IG.py", line 165, in run_IG
    ig_service.create_session()
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 393, in create_session
    self._set_headers(response.headers, True)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 450, in _set_headers
    self.CLIENT_TOKEN = response_headers['CST']
                        ~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\requests\structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
           ~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'cst'
2024-08-03 13:06:12,119 - WARNING - Not Found: /backend-control/images/favicon.ico
2024-08-03 13:15:24,333 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-03 13:15:24,334 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-03 13:15:24,334 - INFO - Scheduler started
2024-08-03 13:15:26,500 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-03 13:15:26,500 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-03 13:15:26,500 - INFO - Scheduler started
2024-08-03 13:15:26,519 - INFO - Watching for file changes with StatReloader
2024-08-03 13:16:00,007 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-03 13:16:00 BST)" (scheduled at 2024-08-03 13:16:00+01:00)
2024-08-03 13:16:00,007 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-03 13:21:00 BST)" (scheduled at 2024-08-03 13:16:00+01:00)
2024-08-03 13:16:00,198 - INFO - The input start time: 2024-08-03 12:00:00
2024-08-03 13:16:00,202 - INFO - The input start time: 2024-08-03 12:00:00
2024-08-03 13:16:18,250 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-03 13:21:00 BST)" executed successfully
2024-08-03 13:16:19,353 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-03 13:21:00 BST)" executed successfully
2024-08-03 13:17:15,458 - WARNING - Not Found: /ml_models/ml-report/images/favicon.ico
2024-08-03 13:20:52,088 - WARNING - Not Found: /news/get-news/images/favicon.ico
2024-08-03 13:21:00,004 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-03 13:26:00 BST)" (scheduled at 2024-08-03 13:21:00+01:00)
2024-08-03 13:21:00,005 - INFO - The input start time: 2024-08-03 12:00:00
2024-08-03 13:21:00,055 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-03 13:26:00 BST)" (scheduled at 2024-08-03 13:21:00+01:00)
2024-08-03 13:21:00,077 - INFO - The input start time: 2024-08-03 12:00:00
2024-08-03 13:21:17,868 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-03 13:26:00 BST)" executed successfully
2024-08-03 13:21:26,714 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-03 13:26:00 BST)" executed successfully
2024-08-03 13:26:33,248 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-03 13:26:33,249 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-03 13:26:33,249 - INFO - Scheduler started
2024-08-03 13:26:35,642 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-03 13:26:35,643 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-03 13:26:35,643 - INFO - Scheduler started
2024-08-03 13:26:35,663 - INFO - Watching for file changes with StatReloader
2024-08-03 13:27:01,356 - WARNING - Not Found: /news/upload-news/images/favicon.ico
2024-08-03 13:31:06,725 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-03 13:31:06,725 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-03 13:31:06,725 - INFO - Scheduler started
2024-08-03 13:31:08,983 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-03 13:31:08,983 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-03 13:31:08,983 - INFO - Scheduler started
2024-08-03 13:31:09,001 - INFO - Watching for file changes with StatReloader
2024-08-03 13:59:57,258 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-03 13:59:57,259 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-03 13:59:57,259 - INFO - Scheduler started
2024-08-03 13:59:59,589 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-03 13:59:59,589 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-03 13:59:59,589 - INFO - Scheduler started
2024-08-03 13:59:59,609 - INFO - Watching for file changes with StatReloader
2024-08-03 14:00:10,347 - ERROR - Internal Server Error: /news/upload-news/
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\news\views.py", line 30, in upload_news
    df = pd.read_csv(file)
         ^^
NameError: name 'pd' is not defined
2024-08-03 14:00:24,194 - INFO - C:\Users\sunny\Desktop\Development\python\TradePro\news\views.py changed, reloading.
2024-08-03 14:00:27,725 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-03 14:00:27,725 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-03 14:00:27,725 - INFO - Scheduler started
2024-08-03 14:00:27,756 - INFO - Watching for file changes with StatReloader
2024-08-03 14:01:00,011 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-03 14:01:00 BST)" (scheduled at 2024-08-03 14:01:00+01:00)
2024-08-03 14:01:00,011 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-03 14:06:00 BST)" (scheduled at 2024-08-03 14:01:00+01:00)
2024-08-03 14:01:00,212 - INFO - The input start time: 2024-08-03 13:00:00
2024-08-03 14:01:00,213 - INFO - The input start time: 2024-08-03 13:00:00
2024-08-03 14:01:01,487 - ERROR - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-03 14:06:00 BST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\updater.py", line 73, in run_procedure_sequence
    run_IG(ticker)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\run_IG.py", line 165, in run_IG
    ig_service.create_session()
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 393, in create_session
    self._set_headers(response.headers, True)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 450, in _set_headers
    self.CLIENT_TOKEN = response_headers['CST']
                        ~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\requests\structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
           ~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'cst'
2024-08-03 14:01:33,464 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-03 14:06:00 BST)" executed successfully
2024-08-03 14:06:00,016 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-03 14:11:00 BST)" (scheduled at 2024-08-03 14:06:00+01:00)
2024-08-03 14:06:00,016 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-03 14:11:00 BST)" (scheduled at 2024-08-03 14:06:00+01:00)
2024-08-03 14:06:00,021 - INFO - The input start time: 2024-08-03 13:00:00
2024-08-03 14:06:00,021 - INFO - The input start time: 2024-08-03 13:00:00
2024-08-03 14:06:00,644 - ERROR - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-03 14:11:00 BST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\updater.py", line 73, in run_procedure_sequence
    run_IG(ticker)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\run_IG.py", line 165, in run_IG
    ig_service.create_session()
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 393, in create_session
    self._set_headers(response.headers, True)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 450, in _set_headers
    self.CLIENT_TOKEN = response_headers['CST']
                        ~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\requests\structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
           ~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'cst'
2024-08-03 14:06:15,381 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-03 14:11:00 BST)" executed successfully
2024-08-03 14:11:00,002 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-03 14:16:00 BST)" (scheduled at 2024-08-03 14:11:00+01:00)
2024-08-03 14:11:00,002 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-03 14:16:00 BST)" (scheduled at 2024-08-03 14:11:00+01:00)
2024-08-03 14:11:00,008 - INFO - The input start time: 2024-08-03 13:00:00
2024-08-03 14:11:00,009 - INFO - The input start time: 2024-08-03 13:00:00
2024-08-03 14:11:01,296 - ERROR - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-03 14:16:00 BST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\updater.py", line 73, in run_procedure_sequence
    run_IG(ticker)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\run_IG.py", line 165, in run_IG
    ig_service.create_session()
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 393, in create_session
    self._set_headers(response.headers, True)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 450, in _set_headers
    self.CLIENT_TOKEN = response_headers['CST']
                        ~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\requests\structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
           ~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'cst'
2024-08-03 14:11:18,380 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-03 14:16:00 BST)" executed successfully
2024-08-03 14:16:48,957 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-03 14:16:48,957 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-03 14:16:48,957 - INFO - Scheduler started
2024-08-03 14:16:51,383 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-03 14:16:51,384 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-03 14:16:51,384 - INFO - Scheduler started
2024-08-03 14:16:51,404 - INFO - Watching for file changes with StatReloader
2024-08-03 14:21:09,870 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-03 14:21:09,870 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-03 14:21:09,870 - INFO - Scheduler started
2024-08-03 14:21:12,263 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-03 14:21:12,263 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-03 14:21:12,263 - INFO - Scheduler started
2024-08-03 14:21:12,285 - INFO - Watching for file changes with StatReloader
2024-08-03 14:21:26,718 - WARNING - Not Found: /ml_models/model-accuracy/images/favicon.ico
2024-08-03 14:25:31,284 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-03 14:25:31,284 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-03 14:25:31,284 - INFO - Scheduler started
2024-08-03 14:25:33,591 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-03 14:25:33,591 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-03 14:25:33,591 - INFO - Scheduler started
2024-08-03 14:25:33,613 - INFO - Watching for file changes with StatReloader
2024-08-03 14:26:00,007 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-03 14:26:00 BST)" (scheduled at 2024-08-03 14:26:00+01:00)
2024-08-03 14:26:00,007 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-03 14:31:00 BST)" (scheduled at 2024-08-03 14:26:00+01:00)
2024-08-03 14:26:00,252 - INFO - The input start time: 2024-08-03 13:00:00
2024-08-03 14:26:00,252 - INFO - The input start time: 2024-08-03 13:00:00
2024-08-03 14:26:01,229 - ERROR - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-03 14:31:00 BST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\updater.py", line 73, in run_procedure_sequence
    run_IG(ticker)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\run_IG.py", line 165, in run_IG
    ig_service.create_session()
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 393, in create_session
    self._set_headers(response.headers, True)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 450, in _set_headers
    self.CLIENT_TOKEN = response_headers['CST']
                        ~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\requests\structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
           ~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'cst'
2024-08-03 14:26:29,709 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-03 14:31:00 BST)" executed successfully
2024-08-03 16:44:34,469 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-03 16:44:34,469 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-03 16:44:34,469 - INFO - Scheduler started
2024-08-03 16:44:36,688 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-03 16:44:36,688 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-03 16:44:36,688 - INFO - Scheduler started
2024-08-03 16:44:36,707 - INFO - Watching for file changes with StatReloader
2024-08-03 16:44:39,229 - WARNING - Not Found: /images/favicon.ico
2024-08-03 16:44:44,191 - ERROR - Internal Server Error: /ml_models/ml-report/
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py", line 338, in ml_report2
    original_date = original_date.replace(tzinfo=pytz.utc)
                    ^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'original_date' where it is not associated with a value
2024-08-03 16:44:44,293 - WARNING - Not Found: /favicon.ico
2024-08-03 16:45:11,276 - INFO - C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py changed, reloading.
2024-08-03 16:45:14,457 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-03 16:45:14,457 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-03 16:45:14,457 - INFO - Scheduler started
2024-08-03 16:45:14,480 - INFO - Watching for file changes with StatReloader
2024-08-03 16:45:16,042 - ERROR - Internal Server Error: /ml_models/ml-report/
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py", line 338, in ml_report2
    original_date = original_date.replace(tzinfo=pytz.utc)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: str.replace() takes no keyword arguments
2024-08-03 16:46:00,006 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-03 16:46:00 BST)" (scheduled at 2024-08-03 16:46:00+01:00)
2024-08-03 16:46:00,006 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-03 16:46:00 BST)" (scheduled at 2024-08-03 16:46:00+01:00)
2024-08-03 16:46:00,189 - INFO - The input start time: 2024-08-03 15:00:00
2024-08-03 16:46:00,189 - INFO - The input start time: 2024-08-03 15:00:00
2024-08-03 16:46:00,874 - ERROR - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-03 16:51:00 BST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\updater.py", line 73, in run_procedure_sequence
    run_IG(ticker)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\run_IG.py", line 165, in run_IG
    ig_service.create_session()
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 393, in create_session
    self._set_headers(response.headers, True)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 450, in _set_headers
    self.CLIENT_TOKEN = response_headers['CST']
                        ~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\requests\structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
           ~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'cst'
2024-08-03 16:46:17,436 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-03 16:51:00 BST)" executed successfully
2024-08-03 16:47:15,193 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-03 16:47:15,193 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-03 16:47:15,193 - INFO - Scheduler started
2024-08-03 16:47:17,499 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-03 16:47:17,499 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-03 16:47:17,499 - INFO - Scheduler started
2024-08-03 16:47:17,519 - INFO - Watching for file changes with StatReloader
2024-08-03 16:47:26,766 - WARNING - Not Found: /ml_models/ml-report/images/favicon.ico
2024-08-03 16:59:03,572 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-03 16:59:03,573 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-03 16:59:03,573 - INFO - Scheduler started
2024-08-03 16:59:05,781 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-03 16:59:05,781 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-03 16:59:05,781 - INFO - Scheduler started
2024-08-03 16:59:05,803 - INFO - Watching for file changes with StatReloader
2024-08-03 16:59:24,295 - WARNING - Not Found: /ml_models/about/images/favicon.ico
2024-08-03 17:01:00,008 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-03 17:01:00 BST)" (scheduled at 2024-08-03 17:01:00+01:00)
2024-08-03 17:01:00,178 - INFO - The input start time: 2024-08-03 16:00:00
2024-08-03 17:01:00,178 - INFO - The input start time: 2024-08-03 16:00:00
2024-08-03 17:01:01,094 - ERROR - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-03 17:06:00 BST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\updater.py", line 73, in run_procedure_sequence
    run_IG(ticker)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\run_IG.py", line 165, in run_IG
    ig_service.create_session()
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 393, in create_session
    self._set_headers(response.headers, True)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 450, in _set_headers
    self.CLIENT_TOKEN = response_headers['CST']
                        ~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\requests\structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
           ~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'cst'
2024-08-03 17:01:20,074 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-03 17:06:00 BST)" executed successfully
2024-08-03 17:06:00,011 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-03 17:11:00 BST)" (scheduled at 2024-08-03 17:06:00+01:00)
2024-08-03 17:06:00,011 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-03 17:11:00 BST)" (scheduled at 2024-08-03 17:06:00+01:00)
2024-08-03 17:06:00,015 - INFO - The input start time: 2024-08-03 16:00:00
2024-08-03 17:06:00,016 - INFO - The input start time: 2024-08-03 16:00:00
2024-08-03 17:06:22,412 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-03 17:11:00 BST)" executed successfully
2024-08-03 17:06:23,341 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-03 17:11:00 BST)" executed successfully
2024-08-03 17:06:42,584 - WARNING - Not Found: /news/get-news/images/favicon.ico
2024-08-03 20:41:11,760 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-03 20:41:11,760 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-03 20:41:11,760 - INFO - Scheduler started
2024-08-03 20:41:14,185 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-03 20:41:14,185 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-03 20:41:14,185 - INFO - Scheduler started
2024-08-03 20:41:14,205 - INFO - Watching for file changes with StatReloader
2024-08-03 20:41:17,651 - WARNING - Not Found: /images/favicon.ico
2024-08-03 20:41:19,512 - WARNING - Not Found: /news/get-news/images/favicon.ico
2024-08-03 20:46:55,878 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-03 20:46:55,878 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-03 20:46:55,878 - INFO - Scheduler started
2024-08-03 20:46:58,197 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-03 20:46:58,197 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-03 20:46:58,198 - INFO - Scheduler started
2024-08-03 20:46:58,220 - INFO - Watching for file changes with StatReloader
2024-08-03 20:47:15,883 - WARNING - Not Found: /ml_models/ml-news-model/images/favicon.ico
2024-08-03 20:48:32,487 - WARNING - Not Found: /ml_models/ml-report/images/favicon.ico
2024-08-03 20:48:37,128 - WARNING - Not Found: /tickers/images/favicon.ico
2024-08-03 20:48:39,679 - WARNING - Not Found: /ml_models/about/images/favicon.ico
2024-08-03 20:49:04,525 - WARNING - Not Found: /ml_models/ml-manual/images/favicon.ico
2024-08-03 20:55:07,000 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-03 20:55:07,001 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-03 20:55:07,001 - INFO - Scheduler started
2024-08-03 20:55:09,307 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-03 20:55:09,307 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-03 20:55:09,307 - INFO - Scheduler started
2024-08-03 20:55:09,326 - INFO - Watching for file changes with StatReloader
2024-08-03 20:58:26,912 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-03 20:58:26,913 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-03 20:58:26,913 - INFO - Scheduler started
2024-08-03 20:58:29,247 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-03 20:58:29,247 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-03 20:58:29,247 - INFO - Scheduler started
2024-08-03 20:58:29,267 - INFO - Watching for file changes with StatReloader
2024-08-03 20:59:52,670 - WARNING - Not Found: /login/images/favicon.ico
2024-08-03 21:02:02,300 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-03 21:02:02,300 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-03 21:02:02,300 - INFO - Scheduler started
2024-08-03 21:02:04,759 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-03 21:02:04,759 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-03 21:02:04,759 - INFO - Scheduler started
2024-08-03 21:02:04,782 - INFO - Watching for file changes with StatReloader
2024-08-03 21:02:15,119 - ERROR - Internal Server Error: /ml_models/ml-news-model/
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py", line 659, in ml_news_model
    user_input = news_param_input(form)
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\manual_model_input.py", line 38, in news_param_input
    model_input['bb_status_1'] = [form.cleaned_data['bb_status_1']]
                                  ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'bb_status_1'
2024-08-03 21:02:15,223 - WARNING - Not Found: /favicon.ico
2024-08-03 21:03:43,080 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-03 21:03:43,081 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-03 21:03:43,081 - INFO - Scheduler started
2024-08-03 21:03:45,388 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-03 21:03:45,388 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-03 21:03:45,388 - INFO - Scheduler started
2024-08-03 21:03:45,406 - INFO - Watching for file changes with StatReloader
2024-08-03 21:03:54,307 - ERROR - Internal Server Error: /ml_models/ml-news-model/
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py", line 659, in ml_news_model
    user_input = news_param_input(form)
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\manual_model_input.py", line 38, in news_param_input
    model_input['bb_status_1'] = [form.cleaned_data['bb_status_1']]
                                  ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'bb_status_1'
2024-08-03 21:05:22,124 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-03 21:05:22,124 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-03 21:05:22,124 - INFO - Scheduler started
2024-08-03 21:05:24,364 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-03 21:05:24,364 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-03 21:05:24,364 - INFO - Scheduler started
2024-08-03 21:05:24,386 - INFO - Watching for file changes with StatReloader
2024-08-03 21:06:00,005 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-03 21:06:00 BST)" (scheduled at 2024-08-03 21:06:00+01:00)
2024-08-03 21:06:00,005 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-03 21:11:00 BST)" (scheduled at 2024-08-03 21:06:00+01:00)
2024-08-03 21:06:00,233 - INFO - The input start time: 2024-08-03 20:00:00
2024-08-03 21:06:00,234 - INFO - The input start time: 2024-08-03 20:00:00
2024-08-03 21:06:01,245 - ERROR - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-03 21:11:00 BST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\updater.py", line 73, in run_procedure_sequence
    run_IG(ticker)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\run_IG.py", line 165, in run_IG
    ig_service.create_session()
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 393, in create_session
    self._set_headers(response.headers, True)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 450, in _set_headers
    self.CLIENT_TOKEN = response_headers['CST']
                        ~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\requests\structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
           ~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'cst'
2024-08-03 21:06:22,367 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-03 21:11:00 BST)" executed successfully
2024-08-03 21:16:30,622 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-03 21:16:30,622 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-03 21:16:30,622 - INFO - Scheduler started
2024-08-03 21:16:32,976 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-03 21:16:32,976 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-03 21:16:32,976 - INFO - Scheduler started
2024-08-03 21:16:32,995 - INFO - Watching for file changes with StatReloader
2024-08-03 21:32:06,264 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-03 21:32:06,264 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-03 21:32:06,264 - INFO - Scheduler started
2024-08-03 21:32:08,525 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-03 21:32:08,525 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-03 21:32:08,525 - INFO - Scheduler started
2024-08-03 21:32:08,546 - INFO - Watching for file changes with StatReloader
2024-08-03 21:32:11,585 - WARNING - Not Found: /images/favicon.ico
2024-08-03 21:32:13,126 - WARNING - Not Found: /ml_models/about/images/favicon.ico
2024-08-03 21:36:00,005 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-03 21:36:00 BST)" (scheduled at 2024-08-03 21:36:00+01:00)
2024-08-03 21:36:00,005 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-03 21:36:00 BST)" (scheduled at 2024-08-03 21:36:00+01:00)
2024-08-03 21:36:00,158 - INFO - The input start time: 2024-08-03 20:00:00
2024-08-03 21:36:00,158 - INFO - The input start time: 2024-08-03 20:00:00
2024-08-03 21:36:01,035 - ERROR - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-03 21:41:00 BST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\updater.py", line 73, in run_procedure_sequence
    run_IG(ticker)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\run_IG.py", line 165, in run_IG
    ig_service.create_session()
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 393, in create_session
    self._set_headers(response.headers, True)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 450, in _set_headers
    self.CLIENT_TOKEN = response_headers['CST']
                        ~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\requests\structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
           ~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'cst'
2024-08-03 21:36:17,878 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-03 21:41:00 BST)" executed successfully
2024-08-03 21:41:00,014 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-03 21:46:00 BST)" (scheduled at 2024-08-03 21:41:00+01:00)
2024-08-03 21:41:00,014 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-03 21:46:00 BST)" (scheduled at 2024-08-03 21:41:00+01:00)
2024-08-03 21:41:00,016 - INFO - The input start time: 2024-08-03 20:00:00
2024-08-03 21:41:00,016 - INFO - The input start time: 2024-08-03 20:00:00
2024-08-03 21:41:00,689 - ERROR - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-03 21:46:00 BST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\updater.py", line 73, in run_procedure_sequence
    run_IG(ticker)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\run_IG.py", line 165, in run_IG
    ig_service.create_session()
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 393, in create_session
    self._set_headers(response.headers, True)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 450, in _set_headers
    self.CLIENT_TOKEN = response_headers['CST']
                        ~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\requests\structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
           ~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'cst'
2024-08-03 21:41:17,987 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-03 21:46:00 BST)" executed successfully
2024-08-03 21:45:18,060 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-03 21:45:18,060 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-03 21:45:18,060 - INFO - Scheduler started
2024-08-03 21:45:20,485 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-03 21:45:20,485 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-03 21:45:20,486 - INFO - Scheduler started
2024-08-03 21:45:20,506 - INFO - Watching for file changes with StatReloader
2024-08-03 21:46:00,003 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-03 21:46:00 BST)" (scheduled at 2024-08-03 21:46:00+01:00)
2024-08-03 21:46:00,003 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-03 21:51:00 BST)" (scheduled at 2024-08-03 21:46:00+01:00)
2024-08-03 21:46:00,161 - INFO - The input start time: 2024-08-03 20:00:00
2024-08-03 21:46:00,161 - INFO - The input start time: 2024-08-03 20:00:00
2024-08-03 21:46:00,777 - WARNING - Not Found: /news/get-news/images/favicon.ico
2024-08-03 21:46:01,102 - ERROR - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-03 21:51:00 BST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\updater.py", line 73, in run_procedure_sequence
    run_IG(ticker)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\run_IG.py", line 165, in run_IG
    ig_service.create_session()
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 393, in create_session
    self._set_headers(response.headers, True)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 450, in _set_headers
    self.CLIENT_TOKEN = response_headers['CST']
                        ~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\requests\structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
           ~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'cst'
2024-08-03 21:46:01,103 - ERROR - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-03 21:51:00 BST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\updater.py", line 73, in run_procedure_sequence
    run_IG(ticker)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\run_IG.py", line 165, in run_IG
    ig_service.create_session()
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 393, in create_session
    self._set_headers(response.headers, True)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 450, in _set_headers
    self.CLIENT_TOKEN = response_headers['CST']
                        ~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\requests\structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
           ~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'cst'
2024-08-03 21:46:08,033 - WARNING - Not Found: /ml_models/ml-report/images/favicon.ico
2024-08-03 21:47:51,194 - WARNING - Not Found: /ml_models/ml-news-model/images/favicon.ico
2024-08-03 21:48:09,874 - WARNING - Not Found: /login/images/favicon.ico
2024-08-03 21:48:15,828 - WARNING - Not Found: /account/images/favicon.ico
2024-08-03 21:48:53,005 - WARNING - Not Found: /news/upload-news/images/favicon.ico
2024-08-03 21:52:10,187 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-03 21:52:10,188 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-03 21:52:10,188 - INFO - Scheduler started
2024-08-03 21:52:12,726 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-03 21:52:12,728 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-03 21:52:12,728 - INFO - Scheduler started
2024-08-03 21:52:12,757 - INFO - Watching for file changes with StatReloader
2024-08-04 03:33:14,701 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-04 03:33:14,701 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-04 03:33:14,701 - INFO - Scheduler started
2024-08-04 03:33:17,249 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-04 03:33:17,249 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-04 03:33:17,249 - INFO - Scheduler started
2024-08-04 03:33:17,279 - INFO - Watching for file changes with StatReloader
2024-08-04 03:33:19,711 - WARNING - Not Found: /images/favicon.ico
2024-08-04 03:40:54,602 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-04 03:40:54,602 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-04 03:40:54,602 - INFO - Scheduler started
2024-08-04 03:40:57,166 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-04 03:40:57,166 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-04 03:40:57,166 - INFO - Scheduler started
2024-08-04 03:40:57,191 - INFO - Watching for file changes with StatReloader
2024-08-04 03:41:00,011 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-04 03:41:00 BST)" (scheduled at 2024-08-04 03:41:00+01:00)
2024-08-04 03:41:00,215 - INFO - The input start time: 2024-08-04 02:00:00
2024-08-04 03:41:00,215 - INFO - The input start time: 2024-08-04 02:00:00
2024-08-04 03:41:17,504 - WARNING - Not Found: /images/favicon.ico
2024-08-04 03:41:17,924 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-04 03:46:00 BST)" executed successfully
2024-08-04 03:41:19,053 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-04 03:46:00 BST)" executed successfully
2024-08-04 03:41:25,267 - WARNING - Not Found: /news/get-news/images/favicon.ico
2024-08-04 03:51:19,162 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-04 03:51:19,162 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-04 03:51:19,162 - INFO - Scheduler started
2024-08-04 03:51:21,670 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-04 03:51:21,670 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-04 03:51:21,670 - INFO - Scheduler started
2024-08-04 03:51:21,696 - INFO - Watching for file changes with StatReloader
2024-08-04 03:51:30,915 - WARNING - Not Found: /ml_models/ml-report/images/favicon.ico
2024-08-04 03:52:24,482 - INFO - C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py changed, reloading.
2024-08-04 03:52:28,069 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-04 03:52:28,069 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-04 03:52:28,069 - INFO - Scheduler started
2024-08-04 03:52:28,094 - INFO - Watching for file changes with StatReloader
2024-08-04 03:54:00,570 - INFO - C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py changed, reloading.
2024-08-04 03:54:04,390 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-04 03:54:04,390 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-04 03:54:04,390 - INFO - Scheduler started
2024-08-04 03:54:04,421 - INFO - Watching for file changes with StatReloader
2024-08-04 03:54:18,148 - WARNING - Not Found: /tickers/images/favicon.ico
2024-08-04 03:55:07,406 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-04 03:55:07,406 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-04 03:55:07,406 - INFO - Scheduler started
2024-08-04 03:55:09,953 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-04 03:55:09,953 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-04 03:55:09,953 - INFO - Scheduler started
2024-08-04 03:55:09,975 - INFO - Watching for file changes with StatReloader
2024-08-04 03:56:00,010 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-04 03:56:00 BST)" (scheduled at 2024-08-04 03:56:00+01:00)
2024-08-04 03:56:00,010 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-04 04:01:00 BST)" (scheduled at 2024-08-04 03:56:00+01:00)
2024-08-04 03:56:00,185 - INFO - The input start time: 2024-08-04 02:00:00
2024-08-04 03:56:00,186 - INFO - The input start time: 2024-08-04 02:00:00
2024-08-04 03:56:01,090 - ERROR - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-04 04:01:00 BST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\updater.py", line 73, in run_procedure_sequence
    run_IG(ticker)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\run_IG.py", line 165, in run_IG
    ig_service.create_session()
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 393, in create_session
    self._set_headers(response.headers, True)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 450, in _set_headers
    self.CLIENT_TOKEN = response_headers['CST']
                        ~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\requests\structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
           ~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'cst'
2024-08-04 03:56:16,745 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-04 04:01:00 BST)" executed successfully
2024-08-04 03:58:35,005 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-04 03:58:35,005 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-04 03:58:35,005 - INFO - Scheduler started
2024-08-04 03:58:37,564 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-04 03:58:37,564 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-04 03:58:37,564 - INFO - Scheduler started
2024-08-04 03:58:37,587 - INFO - Watching for file changes with StatReloader
2024-08-04 04:01:00,015 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-04 04:01:00 BST)" (scheduled at 2024-08-04 04:01:00+01:00)
2024-08-04 04:01:00,015 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-04 04:06:00 BST)" (scheduled at 2024-08-04 04:01:00+01:00)
2024-08-04 04:01:00,224 - INFO - The input start time: 2024-08-04 03:00:00
2024-08-04 04:01:00,228 - INFO - The input start time: 2024-08-04 03:00:00
2024-08-04 04:01:01,007 - ERROR - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-04 04:06:00 BST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\updater.py", line 73, in run_procedure_sequence
    run_IG(ticker)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\run_IG.py", line 165, in run_IG
    ig_service.create_session()
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 393, in create_session
    self._set_headers(response.headers, True)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 450, in _set_headers
    self.CLIENT_TOKEN = response_headers['CST']
                        ~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\requests\structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
           ~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'cst'
2024-08-04 04:01:01,005 - ERROR - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-04 04:06:00 BST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\updater.py", line 73, in run_procedure_sequence
    run_IG(ticker)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\run_IG.py", line 165, in run_IG
    ig_service.create_session()
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 393, in create_session
    self._set_headers(response.headers, True)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 450, in _set_headers
    self.CLIENT_TOKEN = response_headers['CST']
                        ~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\requests\structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
           ~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'cst'
2024-08-04 04:03:22,978 - INFO - C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py changed, reloading.
2024-08-04 04:03:26,461 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-04 04:03:26,461 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-04 04:03:26,461 - INFO - Scheduler started
2024-08-04 04:03:26,489 - INFO - Watching for file changes with StatReloader
2024-08-04 04:03:49,207 - INFO - C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py changed, reloading.
2024-08-04 04:03:52,659 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-04 04:03:52,661 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-04 04:03:52,661 - INFO - Scheduler started
2024-08-04 04:03:52,697 - INFO - Watching for file changes with StatReloader
2024-08-04 04:03:59,283 - INFO - C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py changed, reloading.
2024-08-04 04:04:02,611 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-04 04:04:02,611 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-04 04:04:02,611 - INFO - Scheduler started
2024-08-04 04:04:02,642 - INFO - Watching for file changes with StatReloader
2024-08-04 04:06:00,002 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-04 04:11:00 BST)" (scheduled at 2024-08-04 04:06:00+01:00)
2024-08-04 04:06:00,003 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-04 04:11:00 BST)" (scheduled at 2024-08-04 04:06:00+01:00)
2024-08-04 04:06:00,005 - INFO - The input start time: 2024-08-04 03:00:00
2024-08-04 04:06:00,159 - INFO - The input start time: 2024-08-04 03:00:00
2024-08-04 04:06:00,693 - ERROR - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-04 04:11:00 BST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\updater.py", line 73, in run_procedure_sequence
    run_IG(ticker)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\run_IG.py", line 165, in run_IG
    ig_service.create_session()
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 393, in create_session
    self._set_headers(response.headers, True)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 450, in _set_headers
    self.CLIENT_TOKEN = response_headers['CST']
                        ~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\requests\structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
           ~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'cst'
2024-08-04 04:06:17,604 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-04 04:11:00 BST)" executed successfully
2024-08-04 04:08:01,791 - INFO - C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py changed, reloading.
2024-08-04 04:08:05,191 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-04 04:08:05,191 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-04 04:08:05,191 - INFO - Scheduler started
2024-08-04 04:08:05,224 - INFO - Watching for file changes with StatReloader
2024-08-04 04:08:35,712 - INFO - C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py changed, reloading.
2024-08-04 04:08:39,363 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-04 04:08:39,363 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-04 04:08:39,363 - INFO - Scheduler started
2024-08-04 04:08:39,387 - INFO - Watching for file changes with StatReloader
2024-08-04 04:09:37,366 - INFO - C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py changed, reloading.
2024-08-04 04:09:40,946 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-04 04:09:40,946 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-04 04:09:40,946 - INFO - Scheduler started
2024-08-04 04:09:40,975 - INFO - Watching for file changes with StatReloader
2024-08-04 04:11:27,728 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-04 04:11:27,728 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-04 04:11:27,728 - INFO - Scheduler started
2024-08-04 04:11:30,536 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-04 04:11:30,538 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-04 04:11:30,538 - INFO - Scheduler started
2024-08-04 04:11:30,567 - INFO - Watching for file changes with StatReloader
2024-08-04 04:18:53,016 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-04 04:18:53,016 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-04 04:18:53,016 - INFO - Scheduler started
2024-08-04 04:18:55,660 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-04 04:18:55,660 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-04 04:18:55,660 - INFO - Scheduler started
2024-08-04 04:18:55,690 - INFO - Watching for file changes with StatReloader
2024-08-04 04:21:00,005 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-04 04:21:00 BST)" (scheduled at 2024-08-04 04:21:00+01:00)
2024-08-04 04:21:00,005 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-04 04:26:00 BST)" (scheduled at 2024-08-04 04:21:00+01:00)
2024-08-04 04:21:00,183 - INFO - The input start time: 2024-08-04 03:00:00
2024-08-04 04:21:00,183 - INFO - The input start time: 2024-08-04 03:00:00
2024-08-04 04:21:23,968 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-04 04:26:00 BST)" executed successfully
2024-08-04 04:21:31,246 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-04 04:26:00 BST)" executed successfully
2024-08-04 04:25:41,890 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-04 04:25:41,891 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-04 04:25:41,891 - INFO - Scheduler started
2024-08-04 04:25:44,637 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-04 04:25:44,637 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-04 04:25:44,637 - INFO - Scheduler started
2024-08-04 04:25:44,668 - INFO - Watching for file changes with StatReloader
2024-08-04 04:26:00,009 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-04 04:26:00 BST)" (scheduled at 2024-08-04 04:26:00+01:00)
2024-08-04 04:26:00,009 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-04 04:31:00 BST)" (scheduled at 2024-08-04 04:26:00+01:00)
2024-08-04 04:26:00,221 - INFO - The input start time: 2024-08-04 03:00:00
2024-08-04 04:26:00,222 - INFO - The input start time: 2024-08-04 03:00:00
2024-08-04 04:26:23,555 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-04 04:31:00 BST)" executed successfully
2024-08-04 04:26:24,382 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-04 04:31:00 BST)" executed successfully
2024-08-04 04:30:44,706 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-04 04:30:44,707 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-04 04:30:44,707 - INFO - Scheduler started
2024-08-04 04:30:47,409 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-04 04:30:47,409 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-04 04:30:47,409 - INFO - Scheduler started
2024-08-04 04:30:47,427 - INFO - Watching for file changes with StatReloader
2024-08-04 04:31:00,007 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-04 04:31:00 BST)" (scheduled at 2024-08-04 04:31:00+01:00)
2024-08-04 04:31:00,007 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-04 04:36:00 BST)" (scheduled at 2024-08-04 04:31:00+01:00)
2024-08-04 04:31:00,213 - INFO - The input start time: 2024-08-04 03:00:00
2024-08-04 04:31:00,226 - INFO - The input start time: 2024-08-04 03:00:00
2024-08-04 04:31:01,180 - ERROR - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-04 04:36:00 BST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\updater.py", line 73, in run_procedure_sequence
    run_IG(ticker)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\run_IG.py", line 165, in run_IG
    ig_service.create_session()
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 393, in create_session
    self._set_headers(response.headers, True)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 450, in _set_headers
    self.CLIENT_TOKEN = response_headers['CST']
                        ~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\requests\structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
           ~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'cst'
2024-08-04 04:31:19,232 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-04 04:36:00 BST)" executed successfully
2024-08-04 04:39:05,287 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-04 04:39:05,287 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-04 04:39:05,288 - INFO - Scheduler started
2024-08-04 04:39:07,932 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-04 04:39:07,932 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-04 04:39:07,932 - INFO - Scheduler started
2024-08-04 04:39:07,961 - INFO - Watching for file changes with StatReloader
2024-08-04 04:39:14,166 - ERROR - Internal Server Error: /news/get-news/
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\news\views.py", line 96, in get_news
    date_obj = datetime.strptime(date_str, '%Y-%m-%d').date()
               ^^^^^^^^^^^^^^^^^
AttributeError: module 'datetime' has no attribute 'strptime'
2024-08-04 04:39:14,287 - WARNING - Not Found: /favicon.ico
2024-08-04 04:39:28,279 - INFO - C:\Users\sunny\Desktop\Development\python\TradePro\news\views.py changed, reloading.
2024-08-04 04:39:31,945 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-04 04:39:31,945 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-04 04:39:31,946 - INFO - Scheduler started
2024-08-04 04:39:31,975 - INFO - Watching for file changes with StatReloader
2024-08-04 04:39:42,336 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-04 04:39:42,336 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-04 04:39:42,336 - INFO - Scheduler started
2024-08-04 04:39:44,726 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-04 04:39:44,726 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-04 04:39:44,726 - INFO - Scheduler started
2024-08-04 04:39:44,754 - INFO - Watching for file changes with StatReloader
2024-08-04 04:47:25,373 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-04 04:47:25,374 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-04 04:47:25,374 - INFO - Scheduler started
2024-08-04 04:47:27,934 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-04 04:47:27,934 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-04 04:47:27,934 - INFO - Scheduler started
2024-08-04 04:47:27,957 - INFO - Watching for file changes with StatReloader
2024-08-04 04:49:53,333 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-04 04:49:53,334 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-04 04:49:53,334 - INFO - Scheduler started
2024-08-04 04:49:56,010 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-04 04:49:56,010 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-04 04:49:56,010 - INFO - Scheduler started
2024-08-04 04:49:56,037 - INFO - Watching for file changes with StatReloader
2024-08-04 04:51:00,011 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-04 04:51:00 BST)" (scheduled at 2024-08-04 04:51:00+01:00)
2024-08-04 04:51:00,011 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-04 04:56:00 BST)" (scheduled at 2024-08-04 04:51:00+01:00)
2024-08-04 04:51:00,226 - INFO - The input start time: 2024-08-04 03:00:00
2024-08-04 04:51:00,228 - INFO - The input start time: 2024-08-04 03:00:00
2024-08-04 04:51:01,127 - ERROR - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-04 04:56:00 BST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\updater.py", line 73, in run_procedure_sequence
    run_IG(ticker)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\run_IG.py", line 165, in run_IG
    ig_service.create_session()
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 393, in create_session
    self._set_headers(response.headers, True)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 450, in _set_headers
    self.CLIENT_TOKEN = response_headers['CST']
                        ~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\requests\structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
           ~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'cst'
2024-08-04 04:51:19,268 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-04 04:56:00 BST)" executed successfully
2024-08-04 04:54:25,847 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-04 04:54:25,847 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-04 04:54:25,847 - INFO - Scheduler started
2024-08-04 04:54:28,598 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-04 04:54:28,598 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-04 04:54:28,598 - INFO - Scheduler started
2024-08-04 04:54:28,621 - INFO - Watching for file changes with StatReloader
2024-08-04 04:54:33,844 - ERROR - Internal Server Error: /news/get-news/
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\news\views.py", line 101, in get_news
    date_obj = datetime.strptime(date_str, '%Y-%m-%d').date()
               ^^^^^^^^^^^^^^^^^
AttributeError: module 'datetime' has no attribute 'strptime'
2024-08-04 04:55:04,001 - INFO - C:\Users\sunny\Desktop\Development\python\TradePro\news\views.py changed, reloading.
2024-08-04 04:55:07,433 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-04 04:55:07,434 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-04 04:55:07,434 - INFO - Scheduler started
2024-08-04 04:55:07,469 - INFO - Watching for file changes with StatReloader
2024-08-04 04:56:00,012 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-04 04:56:00 BST)" (scheduled at 2024-08-04 04:56:00+01:00)
2024-08-04 04:56:00,012 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-04 05:01:00 BST)" (scheduled at 2024-08-04 04:56:00+01:00)
2024-08-04 04:56:00,181 - INFO - The input start time: 2024-08-04 03:00:00
2024-08-04 04:56:00,181 - INFO - The input start time: 2024-08-04 03:00:00
2024-08-04 04:56:01,044 - ERROR - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-04 05:01:00 BST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\updater.py", line 73, in run_procedure_sequence
    run_IG(ticker)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\run_IG.py", line 165, in run_IG
    ig_service.create_session()
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 393, in create_session
    self._set_headers(response.headers, True)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 450, in _set_headers
    self.CLIENT_TOKEN = response_headers['CST']
                        ~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\requests\structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
           ~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'cst'
2024-08-04 04:56:16,130 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-04 05:01:00 BST)" executed successfully
2024-08-04 04:57:50,875 - WARNING - Not Found: /ml_models/about/images/favicon.ico
2024-08-04 04:58:54,652 - WARNING - Not Found: /login/images/favicon.ico
2024-08-04 04:59:06,846 - WARNING - Not Found: /prices/upload-prices/images/favicon.ico
2024-08-04 04:59:57,687 - WARNING - Not Found: /account/images/favicon.ico
2024-08-04 05:00:03,267 - WARNING - Not Found: /tickers/ticker/9f53d106-491e-43bc-8f19-f91352ee4426/images/favicon.ico
2024-08-04 05:03:02,504 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-04 05:03:02,504 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-04 05:03:02,504 - INFO - Scheduler started
2024-08-04 05:03:05,216 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-04 05:03:05,216 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-04 05:03:05,216 - INFO - Scheduler started
2024-08-04 05:03:05,236 - INFO - Watching for file changes with StatReloader
2024-08-04 05:03:29,638 - WARNING - Not Found: /ml_models/ml-news-model/images/favicon.ico
2024-08-06 19:13:46,147 - INFO - Watching for file changes with StatReloader
2024-08-06 19:14:14,343 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-06 19:14:14,344 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-06 19:14:14,344 - INFO - Scheduler started
2024-08-06 19:14:16,930 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-06 19:14:16,931 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-06 19:14:16,931 - INFO - Scheduler started
2024-08-06 19:14:16,952 - INFO - Watching for file changes with StatReloader
2024-08-06 19:14:20,229 - WARNING - Not Found: /images/favicon.ico
2024-08-06 19:14:31,472 - WARNING - Not Found: /ml_models/ml-report/images/favicon.ico
2024-08-06 19:16:20,552 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-06 19:16:20,552 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-06 19:16:20,552 - INFO - Scheduler started
2024-08-06 19:16:23,012 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-06 19:16:23,012 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-06 19:16:23,012 - INFO - Scheduler started
2024-08-06 19:16:23,032 - INFO - Watching for file changes with StatReloader
2024-08-06 19:16:26,802 - ERROR - Internal Server Error: /ml_models/ml-report/
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py", line 408, in ml_report2
    model_comparer_rev = ModelComparer(pred_reverse_v4, pred_reverse_v5, pred_reverse_1h_v5, 3, 1 )
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\analysis_comments.py", line 58, in __init__
    self.compare_versions()  # Call the comparison method during initialization
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\analysis_comments.py", line 69, in compare_versions
    current_trade1 = array1[self.arr_index].split()[0]
                     ~~~~~~^^^^^^^^^^^^^^^^
IndexError: list index out of range
2024-08-06 19:16:26,934 - WARNING - Not Found: /favicon.ico
2024-08-06 19:16:58,919 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-06 19:16:58,919 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-06 19:16:58,919 - INFO - Scheduler started
2024-08-06 19:17:01,124 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-06 19:17:01,125 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-06 19:17:01,125 - INFO - Scheduler started
2024-08-06 19:17:01,142 - INFO - Watching for file changes with StatReloader
2024-08-06 19:17:06,236 - ERROR - Internal Server Error: /ml_models/ml-report/
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\views.py", line 408, in ml_report2
    model_comparer_rev = ModelComparer(pred_reverse_v4, pred_reverse_v5, pred_reverse_1h_v5, 3, 1 )
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\analysis_comments.py", line 58, in __init__
    self.compare_versions()  # Call the comparison method during initialization
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\ml_models\utils\analysis_comments.py", line 69, in compare_versions
    current_trade1 = array1[self.arr_index].split()[0]
                     ~~~~~~^^^^^^^^^^^^^^^^
IndexError: list index out of range
2024-08-06 19:18:18,685 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-06 19:18:18,685 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-06 19:18:18,685 - INFO - Scheduler started
2024-08-06 19:18:20,891 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-06 19:18:20,891 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-06 19:18:20,891 - INFO - Scheduler started
2024-08-06 19:18:20,909 - INFO - Watching for file changes with StatReloader
2024-08-06 19:21:00,014 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-06 19:21:00 BST)" (scheduled at 2024-08-06 19:21:00+01:00)
2024-08-06 19:21:00,015 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-06 19:26:00 BST)" (scheduled at 2024-08-06 19:21:00+01:00)
2024-08-06 19:21:00,367 - INFO - The input start time: 2024-08-06 18:00:00
2024-08-06 19:21:00,369 - INFO - The input start time: 2024-08-06 18:00:00
2024-08-06 19:21:01,152 - ERROR - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-06 19:26:00 BST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\updater.py", line 73, in run_procedure_sequence
    run_IG(ticker)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\run_IG.py", line 165, in run_IG
    ig_service.create_session()
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 393, in create_session
    self._set_headers(response.headers, True)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 450, in _set_headers
    self.CLIENT_TOKEN = response_headers['CST']
                        ~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\requests\structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
           ~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'cst'
2024-08-06 19:21:19,599 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-06 19:26:00 BST)" executed successfully
2024-08-06 19:26:00,014 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-06 19:31:00 BST)" (scheduled at 2024-08-06 19:26:00+01:00)
2024-08-06 19:26:00,014 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-06 19:31:00 BST)" (scheduled at 2024-08-06 19:26:00+01:00)
2024-08-06 19:26:00,021 - INFO - The input start time: 2024-08-06 18:00:00
2024-08-06 19:26:00,021 - INFO - The input start time: 2024-08-06 18:00:00
2024-08-06 19:26:20,680 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-06 19:31:00 BST)" executed successfully
2024-08-06 19:26:22,425 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-06 19:31:00 BST)" executed successfully
2024-08-06 19:31:00,006 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-06 19:36:00 BST)" (scheduled at 2024-08-06 19:31:00+01:00)
2024-08-06 19:31:00,006 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-06 19:36:00 BST)" (scheduled at 2024-08-06 19:31:00+01:00)
2024-08-06 19:31:00,011 - INFO - The input start time: 2024-08-06 18:00:00
2024-08-06 19:31:00,011 - INFO - The input start time: 2024-08-06 18:00:00
2024-08-06 19:31:21,640 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-06 19:36:00 BST)" executed successfully
2024-08-06 19:31:23,162 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-06 19:36:00 BST)" executed successfully
2024-08-06 19:46:40,296 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-06 19:46:40,296 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-06 19:46:40,296 - INFO - Scheduler started
2024-08-06 19:46:42,600 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-06 19:46:42,601 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-06 19:46:42,601 - INFO - Scheduler started
2024-08-06 19:46:42,622 - INFO - Watching for file changes with StatReloader
2024-08-06 19:50:46,245 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-06 19:50:46,245 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-06 19:50:46,245 - INFO - Scheduler started
2024-08-06 19:50:48,599 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-06 19:50:48,599 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-06 19:50:48,599 - INFO - Scheduler started
2024-08-06 19:50:48,620 - INFO - Watching for file changes with StatReloader
2024-08-06 19:51:00,015 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-06 19:51:00 BST)" (scheduled at 2024-08-06 19:51:00+01:00)
2024-08-06 19:51:00,019 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-06 19:56:00 BST)" (scheduled at 2024-08-06 19:51:00+01:00)
2024-08-06 19:51:00,220 - INFO - The input start time: 2024-08-06 18:00:00
2024-08-06 19:51:00,723 - ERROR - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-06 19:56:00 BST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\updater.py", line 73, in run_procedure_sequence
    run_IG(ticker)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\run_IG.py", line 165, in run_IG
    ig_service.create_session()
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 393, in create_session
    self._set_headers(response.headers, True)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 450, in _set_headers
    self.CLIENT_TOKEN = response_headers['CST']
                        ~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\requests\structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
           ~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'cst'
2024-08-06 19:51:00,952 - INFO - The input start time: 2024-08-06 18:00:00
2024-08-06 19:51:01,485 - ERROR - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-06 19:56:00 BST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\updater.py", line 73, in run_procedure_sequence
    run_IG(ticker)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\run_IG.py", line 165, in run_IG
    ig_service.create_session()
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 393, in create_session
    self._set_headers(response.headers, True)
  File "C:\Users\sunny\Desktop\Development\python\TradePro\prices\IG_session\ig_service.py", line 450, in _set_headers
    self.CLIENT_TOKEN = response_headers['CST']
                        ~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\sunny\anaconda3\envs\myenv311test\Lib\site-packages\requests\structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
           ~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'cst'
2024-08-06 19:52:13,652 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-06 19:52:13,652 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-06 19:52:13,652 - INFO - Scheduler started
2024-08-06 19:52:15,777 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-06 19:52:15,777 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-06 19:52:15,777 - INFO - Scheduler started
2024-08-06 19:52:15,797 - INFO - Watching for file changes with StatReloader
2024-08-06 19:55:19,050 - WARNING - Not Found: /ml_models/about/images/favicon.ico
2024-08-06 19:56:00,014 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-06 19:56:00 BST)" (scheduled at 2024-08-06 19:56:00+01:00)
2024-08-06 19:56:00,014 - INFO - Running job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-06 19:56:00 BST)" (scheduled at 2024-08-06 19:56:00+01:00)
2024-08-06 19:56:00,182 - INFO - The input start time: 2024-08-06 18:00:00
2024-08-06 19:56:00,183 - INFO - The input start time: 2024-08-06 18:00:00
2024-08-06 19:56:17,607 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-06 20:01:00 BST)" executed successfully
2024-08-06 19:56:17,613 - INFO - Job "run_procedure_sequence (trigger: interval[0:05:00], next run at: 2024-08-06 20:01:00 BST)" executed successfully
2024-08-06 20:01:20,901 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-06 20:01:20,902 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-06 20:01:20,902 - INFO - Scheduler started
2024-08-06 20:01:23,099 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-06 20:01:23,100 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-06 20:01:23,100 - INFO - Scheduler started
2024-08-06 20:01:23,117 - INFO - Watching for file changes with StatReloader
2024-08-07 18:50:16,167 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-07 18:50:16,168 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-07 18:50:16,168 - INFO - Scheduler started
2024-08-07 18:50:18,381 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-07 18:50:18,381 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-07 18:50:18,381 - INFO - Scheduler started
2024-08-07 18:50:18,399 - INFO - Watching for file changes with StatReloader
2024-08-07 18:50:20,668 - WARNING - Not Found: /images/favicon.ico
2024-08-07 18:50:29,822 - WARNING - Not Found: /ml_models/ml-report/images/favicon.ico
2024-08-07 19:16:01,899 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-07 19:16:01,899 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-07 19:16:01,899 - INFO - Scheduler started
2024-08-07 19:16:04,070 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-07 19:16:04,070 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-07 19:16:04,070 - INFO - Scheduler started
2024-08-07 19:16:04,092 - INFO - Watching for file changes with StatReloader
2024-08-07 19:16:06,278 - WARNING - Not Found: /images/favicon.ico
2024-08-07 19:16:18,700 - WARNING - Not Found: /ml_models/ml-report/images/favicon.ico
2024-08-07 19:19:12,343 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-07 19:19:12,343 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-07 19:19:12,343 - INFO - Scheduler started
2024-08-07 19:19:14,753 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-07 19:19:14,754 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-07 19:19:14,754 - INFO - Scheduler started
2024-08-07 19:19:14,775 - INFO - Watching for file changes with StatReloader
2024-08-07 19:19:16,503 - WARNING - Not Found: /images/favicon.ico
2024-08-07 19:19:24,644 - WARNING - Not Found: /ml_models/ml-report/images/favicon.ico
2024-08-07 20:17:59,012 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-07 20:17:59,012 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-07 20:17:59,012 - INFO - Scheduler started
2024-08-07 20:18:01,238 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-08-07 20:18:01,239 - INFO - Added job "run_procedure_sequence" to job store "default"
2024-08-07 20:18:01,239 - INFO - Scheduler started
2024-08-07 20:18:01,259 - INFO - Watching for file changes with StatReloader
2024-08-07 20:18:02,927 - WARNING - Not Found: /images/favicon.ico
2024-08-07 20:18:11,071 - WARNING - Not Found: /ml_models/ml-report/images/favicon.ico
2024-08-07 20:18:24,414 - WARNING - Not Found: /ml_models/model-accuracy/images/favicon.ico
